### PR TITLE
#1673 remove unnecessary dependancy ignore check

### PR DESCRIPTION
**Pull request by davidradl**
Signed-off-by: David Radley <david_radley@uk.ibm.com>

### CODE REVIEW

**Comment by planetf1** [comment]
Adding x-ref: Issue for this was reported in: https://github.com/odpi/egeria/issues/1689

**Comment by planetf1** [comment]
checking..

**Comment by planetf1** [comment]
Errors noted testing this change - unfortunately is already merged so will open in new issue:
```
➜  configuration-store-connectors git:(master) ✗ pwd
/Users/jonesn/src/egeria/open-metadata-implementation/adapters/open-connectors/configuration-store-connectors
➜  configuration-store-connectors git:(master) ✗ mvn install
[INFO] Scanning for projects...
[WARNING]
```
➜  configuration-store-connectors git:(master) ✗ pwd
/Users/jonesn/src/egeria/open-metadata-implementation/adapters/open-connectors/configuration-store-connectors
➜  configuration-store-connectors git:(master) ✗ mvn install
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.odpi.egeria:configuration-store-connectors:pom:1.1-SNAPSHOT
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.odpi.egeria:ui-admin-services-client:jar -> duplicate declaration of version ${open-metadata.version} @ org.odpi.egeria:egeria:1.1-SNAPSHOT, /Users/jonesn/IdeaProjects/egeria/pom.xml, line 544, column 25
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
```

I will also raise a seperate issue to see what hard checks can be put in build to avoid any reoccurance

Other changes look good so far thanks

**Comment by davidradl** [comment]
@planetf1 Thanks Nigel - it would be great to pick these up in the build.

**Comment by planetf1** [comment]
Agreed. I try and review them, but this was merged too quickly - we don't (yet?) enforce reviews

**Comment by davidradl** [comment]
@planetf1 Yes sorry - I saw you had updated and assumed you have looked at it - my bad.

**Comment by davidradl** [comment]
@planetf1 where are you seeing the warnings - my local build looks clean?

**Comment by planetf1** [comment]
Probably best we continue in #1697 as this is merged

**Pull request merged**
