### PR TITLE
Docker split

### PR DESCRIPTION
**Pull request by akhilreddyjirra**
This PR will address the below issues. 
1. Docker split for ranger and prebuild ranger distro  Issue #1251
2. Modify docker build in apache-atlas Issue #1250
3. Changes in Pom.xml Issue #1224

### CODE REVIEW

**Comment by planetf1** [comment]
I'm getting
```
12:02:11,060 [ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.10:build (build-and-tag-latest) on project open-metadata-docker-apache-atlas: Could not build image: COPY failed: stat /var/lib/docker/overlay2/a09c8db0ce4fd59e0cccf9cf487677bc8349ed241ea2418809a6e93f4fe4ac40/merged/root/atlas-bin: no such file or directory -> [Help 1]
```
when building from the PR (using -Ddocker -Ddocker.repo=planetf1)

**Comment by planetf1** [comment]
So is reflecting the atlas build prior to the non-root change (which is now in master)

**Comment by planetf1** [comment]
any update on this ?

**Comment by akhilreddyjirra** [comment]
> any update on this ?

Hi @planetf1,
Can you please send me a full log if available.  and the full command also.

**Comment by planetf1** [comment]
I think part of the problem here is that the official 'odpi' repo has been updated beyond the level of code in 'master' - probably as the change was being tested.

This is why using a private repo is useful - for testing.

I think the pragmatic approach is that I'll merge this PR, and then retest, and fix up against master?

**Pull request merged**
