### PR TITLE
Make ranger compile to fix build break

### PR DESCRIPTION
**Pull request by mlottesen**
Update commons.lang to import correct StringUtils version and exclude Eclipse project files from rat check.

### CODE REVIEW

**Comment by planetf1** [comment]
Hi,
 Can you indicate what the build break you saw was? Which aspect failed to build?

 Also I did make some changes to the ranger gaian plugin code in the last few days - partly to bring some dependencies forward (in part also due to rat checks) - this has also meant moving to ranger 1.2

The code is building cleanly on the official build too - not that means there aren't issues!

I notice you have a reference to eclipse (ie ignoring project files) - I know a few developers were using eclipse a while ago, but we're mostly using IntelliJ IDEA now. Great if you can get it to work, but there can sometimes be some friction with lifecycle management & maven.

**Comment by mlottesen** [comment]
The compilation error is in the Ranger Gaian Plugin project....

[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ gaian-ranger-plugin ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 11 source files to C:\builds\OMRS\open-metadata-implementation\adapters\governance-engines-plugins\gaian-ranger-plugin\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /C:/builds/OMRS/open-metadata-implementation/adapters/governance-engines-plugins/gaian-ranger-plugin/src/main/java/org/odpi/openmetadata/adapters/governanceenginesplugins/gaianrangerplugin/RangerGaianAuthorizer.java:[7,31] package org.apache.commons.lang does not exist
[ERROR] /C:/builds/OMRS/open-metadata-implementation/adapters/governance-engines-plugins/gaian-ranger-plugin/src/main/java/org/odpi/openmetadata/adapters/governanceenginesplugins/gaianrangerplugin/RangerGaianAuthorizer.java:[146,17] cannot find symbol
  symbol:   variable StringUtils
  location: class org.odpi.openmetadata.adapters.governanceenginesplugins.gaianrangerplugin.RangerGaianAuthorizer
[ERROR] /C:/builds/OMRS/open-metadata-implementation/adapters/governance-engines-plugins/gaian-ranger-plugin/src/main/java/org/odpi/openmetadata/adapters/governanceenginesplugins/gaianrangerplugin/RangerGaianAuthorizer.java:[148,24] cannot find symbol
  symbol:   variable StringUtils
  location: class org.odpi.openmetadata.adapters.governanceenginesplugins.gaianrangerplugin.RangerGaianAuthorizer
[ERROR] /C:/builds/OMRS/open-metadata-implementation/adapters/governance-engines-plugins/gaian-ranger-plugin/src/main/java/org/odpi/openmetadata/adapters/governanceenginesplugins/gaianrangerplugin/RangerGaianAuthorizer.java:[150,24] cannot find symbol
  symbol:   variable StringUtils
  location: class org.odpi.openmetadata.adapters.governanceenginesplugins.gaianrangerplugin.RangerGaianAuthorizer
[ERROR] /C:/builds/OMRS/open-metadata-implementation/adapters/governance-engines-plugins/gaian-ranger-plugin/src/main/java/org/odpi/openmetadata/adapters/governanceenginesplugins/gaianrangerplugin/RangerGaianAuthorizer.java:[192,61] cannot find symbol
  symbol:   variable StringUtils
  location: class org.odpi.openmetadata.adapters.governanceenginesplugins.gaianrangerplugin.RangerGaianAuthorizer
[INFO] 5 errors 

The move from commons-lang 2.6 to 3.8.1 requires the package name to change from org.apache.commons.lang to lang3 in order to compile.  I've seen this on two different systems.

**Comment by planetf1** [comment]
thanks @mlottesen 

Can you confirm what level of code you are using - ie the latest commit, branch? can you reproduce with a fresh clone? of identified code in github?

Also what JDK are you using? I am using 1.8.0_192-b12 openjdk mostly (hotspot)

today I've built that code with windows/java 8 windows/java 11, mac/java 8, mac /java 9, multiple builds on jenkins.apache.org (PRs & master) and none have hit the issue.

the latest jenkins master build is at https://jenkins.odpi.org/view/odpi-egeria/job/odpi-egeria-maven-merge-master/lastBuild/ which completed ok

I'm not disagreeing the change is appropriate though - it's a good spot & something I should have corrected-- if you can do a PR with just that change in (or we ask mandy to review the other omrs changes) then I'd agree we should merge. I'm ust trying to figure out why your build is failing and others are not :-) I'm guessing perhaps it is in combination with another change? Perhaps something locally that is then causing the underlying issue/omission to show up?

**Comment by planetf1** [comment]
I did a mvn dependency:tree & can see that
 - [INFO] +- org.apache.commons:commons-lang3:jar:3.8.1:compile
is being pulled in as expected from the pom, but also
[INFO] |  |  +- commons-lang:commons-lang:jar:2.6:compile

from [INFO] |  +- org.apache.hadoop:hadoop-common:jar:2.9.2:runtime
which itself was from
[INFO] +- org.apache.ranger:ranger-plugins-common:jar:1.2.0:compile

which I think is why the build is working ok -- it's finding the older library anyway.

This would suggest something in your environment may be different in terms of the ranger plugin code, or hadoop libraries. Any ideas?

Might be worth you also running mvn dependency:tree - I'll attach mine here (off latest master) for reference and we can compare

**Comment by planetf1** [comment]
My current git SHA of head is 4afe973074ec643fca7314ad5b89109a613363d8

My dependency tree is at https://gist.github.com/8ebb04734c31a0cc5f0aad03ba7e7add

**Comment by planetf1** [comment]
Have verified the proposed change - plugin still works, masking applied etc so safe to integrate.
Thanks for the proposal

**Pull request merged**
