### PR TITLE
(Draft) [ui-chassis-spring] remove zuul dependencies

### PR DESCRIPTION
**Pull request by bogdan-sava**

### CODE REVIEW

**Review by planetf1 — COMMENTED** [review]
Agree with removing zuul.
If this is merged, what is the impact on the current docs for running the UI
Also what is the effect on the current container environment (labs & simple). Has it been tested?
I think we need to confirm both before merging, especially as our next release is imminent

**Comment by lpalashevski** [comment]
#4549

**Review by planetf1 — CHANGES_REQUESTED** [review]
This PR removes the requirement for zuul - however without zuul the current approach of launching the UI will no longer be the same. If this changes function we either need to ensure each PR is an incremental update without breakage, or we combine them together in a single PR?

Or is the intent that we do #4723 first ?

If they need to be done together, Taking the commit's and cherrypicking may be the easiest approach

**Comment by planetf1** [comment]
We also need to add documentation, as removal of zuul affects how a user would deploy the UI if they are setting up themselves.

**Comment by sarbull** [comment]
This PR is incomplete, check this one for the complete removal of Zuul Module: https://github.com/odpi/egeria/pull/4922

**Pull request closed without merging**
