### PR TITLE
Introduction of MetadataHighwayServicesClient

### PR DESCRIPTION
**Pull request by grahamwallis**

### CODE REVIEW

**Comment by planetf1** [comment]
The gradle build output is at https://dev.azure.com/ODPi/Egeria/_build/results?buildId=10942&view=results

This failed with an error
```
Execution failed for task ':open-metadata-implementation:repository-services:repository-services-client:compileJava'.
> Compilation failed; see the compiler error output for details.
```
Looking up for more detail we see:
```
/home/vsts/work/1/s/open-metadata-implementation/repository-services/repository-services-client/src/main/java/org/odpi/openmetadata/repositoryservices/clients/MetadataHighwayServicesClient.java:35: error: package org.springframework.web.bind.annotation does not exist
import org.springframework.web.bind.annotation.GetMapping;
                                              ^
/home/vsts/work/1/s/open-metadata-implementation/repository-services/repository-services-client/src/main/java/org/odpi/openmetadata/repositoryservices/clients/MetadataHighwayServicesClient.java:36: error: package org.springframework.web.bind.annotation does not exist
import org.springframework.web.bind.annotation.PathVariable;
                                              ^
/home/vsts/work/1/s/open-metadata-implementation/repository-services/repository-services-client/src/main/java/org/odpi/openmetadata/repositoryservices/clients/MetadataHighwayServicesClient.java:37: error: package org.springframework.web.bind.annotation does not exist
import org.springframework.web.bind.annotation.RequestMapping;
                                              ^
/home/vsts/work/1/s/open-metadata-implementation/repository-services/repository-services-client/src/main/java/org/odpi/openmetadata/repositoryservices/clients/MetadataHighwayServicesClient.java:38: error: package org.springframework.web.bind.annotation does not exist
import org.springframework.web.bind.annotation.RestController;
                                              ^
4 errors

```
This looks like a missing dependency .... will comment later

**Comment by planetf1** [comment]
the build can be repeated with `./gradlew build` from top level dir

**Comment by grahamwallis** [comment]
@planetf1 Thanks Nigel - looks like I had some unused imports lying around. Am just rebuilding with them cleaned up and will repush soon.

**Comment by planetf1** [comment]
The Java 11 build is failing in the open connector framework tests. There looks like an odd fork/class loading issue which I've not seen before.

I cannot see any way your change caused this. My guess is it's an intermittent/one-off error - resource? or is a change in the build environment (the VMs are standard provided by MS, as is java etc)

I would recommend re-pushing to force a new build - or I can run a new build manually and we investigate if it reoccurs...

**Comment by grahamwallis** [comment]
Fixes #3644

**Pull request merged**
