### PR TITLE
Fixes event mapper issues in #543

### PR DESCRIPTION
**Pull request by cmgrote**
Adds provenance type to relationships and actual entity type for entity proxy (not just supertype as previously).

Also sets up AttributeTypeDefs properly as part of initialisation of the IGC connector now, too.

### CODE REVIEW

**Comment by cmgrote** [comment]
^^ @ruxandraRosu @bogdan-sava

**Comment by cmgrote** [comment]
Is there a way I can force a rebuild?  I'm building the same branch locally, with same commits, and it builds fine -- not clear where the compilation error is occurring...

**Comment by ruxandraRosu** [comment]
I've tested branch igc-repo-conn and the relationships are added. There are some issues with UPDATED_ENTITY and UPDATED_RELATIONSHIPS events, these are investigated on atlas connector side.

**Comment by cmgrote** [comment]
(Not sure why it requires significant resources -- in my compiled target for the referenced location it's 36MB ?)

**Comment by cmgrote** [comment]
Will attempt to play with compiler plugin changes and re-test...

**Pull request merged**
