### PR TITLE
#1619 Point to jfrog for docker builds

### PR DESCRIPTION
**Pull request by planetf1**
FYI @bramwelt - these are changes for our docker builds
#1630 should be dependent on this
@cmgrote - may be associated changes in the connector repos

Am opening this for review and for build team, but suggest not merging until they are ready - from my perspective the azure builds are functioning very well now (and quickly) 

Signed-off-by: Nigel Jones <nigel.l.jones+git@gmail.com>

### CODE REVIEW

**Comment by planetf1** [comment]
Note that I suspect the atlas/ranger builds do not require this as they are base images with no egeria dependencies, but since these builds are rarely built, nor automated so far I have made the url change only

**Comment by cmgrote** [comment]
> from my perspective the azure builds are functioning very well now (and quickly)

Agreed!  Their output is also far nicer (and more read-able) 😄

**Comment by planetf1** [comment]
Since we now have both builds running in parallel, nothing should break if either your changes or the one here are merged. It's just us making that call about the switch.

**Comment by planetf1** [comment]
Super - I can confirm the docker build went fine after the change as expected - https://dev.azure.com/odpi/Egeria/_build/results?buildId=257

**Pull request merged**
