### PR TITLE
Switch from springfox to springdoc

### PR DESCRIPTION
**Pull request by planetf1**
Initial PR - currently DRAFT to solicate review comments and aid in bug analysis with springdoc project

See #1124 
* Removes springfox
* Adds springdoc https://github.com/springdoc/springdoc-openapi
* Now moves us on to OpenAPI 3.0
* Better compatibility with newer spring versions & features

This does not (yet) start adding additional swagger2 annotations, groups etc - but is intended to provide a foundation for doing that

NOTE: In draft. If established working will raise proposal at next meeting , prior to any merge.

### CODE REVIEW

**Comment by planetf1** [comment]
(Working through https://github.com/springdoc/springdoc-openapi/issues/486 )

**Comment by planetf1** [comment]
Commit 6b90615 fixes up some usage of @JSonIdentityInfo that was causing the NPE (see the linked issues above). 

It would be very useful if someone more familar with this annotation & specifically InformationView could verify by inspection & execution (ideally). Beyond any unit tests I have no easy way of testing. The owner in CODEOWNERS has left. @danielaotelea perhaps you may know?

With this change the default API docs are now generated, and visible through swagger at http://localhost:8080/swagger-ui.html

I will bring up the proposal  on the next functionality call. 
This change only sets up the basic framework - next we have plenty of work to do on using the proper annotations.

**Comment by planetf1** [comment]
Screenshot 2020-03-13 at 15 01 04

**Comment by planetf1** [comment]
You can see an example of the generated json at https://gist.github.com/d0d38bafe8f50b355e81cc4df714a534

**Comment by planetf1** [comment]
Noted by @davidradl - ensure the developer docs are updated to refer to new approach

**Comment by davidradl** [comment]
As discussed - checking whether we need to update  docs

**Comment by planetf1** [comment]
I have not made any process updates yet.
I propose we discuss this on the next status call 19 Mar 2020.

**Comment by planetf1** [comment]
See https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations for annotation info

**Comment by planetf1** [comment]
Corrected documentation as per status call today. 
Will run an OWASP scan prior to merging

**Pull request merged**
