### PR TITLE
Fixing missing negations on versionName tests, and validation of Attr…

### PR DESCRIPTION
**Pull request by grahamwallis**
…ibuteTypeDef

Signed-off-by: Graham Wallis <graham_wallis@uk.ibm.com>

### CODE REVIEW

**Comment by cmgrote** [comment]
Superseded by #2351 ?

**Comment by mandy-chessell** [comment]
I think so - this just seems to add the `!`s and not the lab notebooks?

**Comment by planetf1** [comment]
> Superseded by #2351 ?

Looks like it - I was applying the patches locally and inspected - looks like the same changes for negation and attributes are in Mandy's change

I think it would be appropriate to merge this soon - any objections? Was just going to run a quick local test

**Comment by cmgrote** [comment]
Closing in light of #2351 merge

**Pull request closed without merging**
