### PR TITLE
Add Dependency on later version of Sleepycat

### PR DESCRIPTION
**Pull request by bramwelt**
The current version of janusgraph-berkeleyje (a dependency of
JanusGraph) relies on an outdated version of com.sleepycat.je that while
available from Oracle's Maven repository[1], it is no longer replicated
to Maven Central.

Thus when building Egeria without a cached version of sleepycat (or
pulling from a Maven repository without the cached version), some users
will continue to experience failures when building Egeria. Specifing a
greater version of sleepycat appears to bypass this failure and allow
the build to succeed.

Resolves: #1116

[1] https://download.oracle.com/maven/com/sleepycat/je/7.4.5/je-7.4.5.pom
Signed-off-by: Trevor Bramwell <tbramwell@linuxfoundation.org>

### CODE REVIEW

**Comment by bramwelt** [comment]
As an aside: I pulled sleepycat 7.4.5 was from Oracle and uploaded it to Artifactory in order for the builds to pass -  I don't think I understand enough of how maven dependency resolution works to explain why builds work someplaces and not others.

**Comment by planetf1** [comment]
This causes us problems due to our use of JanusGraph. See also https://github.com/JanusGraph/janusgraph/issues/1621

At the time the earlier issue was raised we hadn't fully embraced the use of dependencyManagement to aid with transitive dependencies, but we have now - meaning we can  make this kind of change.

The only question is whether there's any concern/impact on the graph. I would expect not as berkeleydb is pretty stable now - and only used for a simple environment. 

Any comments @grahamwallis @mandy-chessell @GuyAckermans

**Comment by bramwelt** [comment]
> The only question is whether there's any concern/impact on the graph. I would expect not as berkeleydb is pretty stable now - and only used for a simple environment.

I think the correct approach here is really to bump the JanusGraph dependency assuming it pulls in the newer version of sleepycat. But I'm not well versed in Egeria to know how much that version change might affect things. :thinking:

**Comment by planetf1** [comment]
recheck

**Pull request merged**
