### PR TITLE
Fixes #6352

### LINKED ISSUE #6352: [BUG] glossary author FVT should not use subject area clients
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I was looking at [https://github.com/odpi/egeria/issues/6326](https://github.com/odpi/egeria/issues/6326) and I noticed that in the glossary author FVT SubjectAreaDefinitionCategoryFVT contains `SubjectAreaNodeClient<SubjectAreaDefinition> subjectAreaCategory = null;` and it uses `SubjectAreaRestClient`. Also TermFVT contains    ` private SubjectAreaNodeClient<Term> subjectAreaTerm = null;`

I think that the glossary author FVT should only use glossary author rest calls so should have no need to create subject area clients. The issue that was raise around security seems to be dealing with SubjectAreaDefinitionCategory I am not sure if this is related.

### Expected Behavior

Do not refer to the subject area FVT clients in the glossary author fvt

### Steps To Reproduce

as above.

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

### Any Further Information?

_No response_

### PR DESCRIPTION
**Pull request by odttlnt**
- Updated SubjectAreaDefinitionCategoryFVT.java to use glossary author endpoints.
- clean up unnecessary code and put log entries instead of sysout
Fixes #6352 

Signed-off-by: Sachin Naik <91499691+odttlnt@users.noreply.github.com>

## Description
A new wrapper class has been defined in the GlossaryAuthorViewFVT. This will be used by the subjectAreaDefinition FVT to perform its testing. 
The other files have been cleaned up to remove unused code and direct SYSOUT messages to log 

## Related Issue(s)

Fixes #6352

## Testing

Junit testing

### CODE REVIEW

**Review by davidradl — APPROVED** [review]

**Comment by davidradl** [comment]
@planetf1 @odttlnt I am not sure why the build is failing - it seems like the build task was killed - it is not obvious this is a code error to me.

**Comment by odttlnt** [comment]
Here is the error message I see, its in > Task :open-metadata-test:open-metadata-fvt:access-services-fvt:asset-consumer-fvt:test
 
  14:34:16.204 [Test worker] ERROR o.o.o.c.ffdc.RESTExceptionHandler - FFDC Response: TagResponse{tag=null, exceptionClassName='org.odpi.openmetadata.frameworks.connectors.ffdc.InvalidParameterException', exceptionCausedBy='null', actionDescription='getTag', relatedHTTPCode=400, exceptionErrorMessage='OMAG-COMMON-400-021 The identifier 3189a937-cc8f-437a-a6d7-c8cc128270de of the InformalTag passed by newUserId to method getTag of service Asset Consumer OMAS is not recognized by the serverinmem server', exceptionErrorMessageId='OMAG-COMMON-400-021', exceptionErrorMessageParameters=[3189a937-cc8f-437a-a6d7-c8cc128270de, InformalTag, newUserId, getTag, Asset Consumer OMAS, serverinmem], exceptionSystemAction='The system is unable to process the request because the identifier is invalid.', exceptionUserAction='Update the caller to provide a correct asset identifier.', exceptionProperties={parameterName=guid}}
    14:34:16.259 [Test worker] ERROR o.o.o.c.ffdc.RESTExceptionHandler - Detected Invalid Parameter Exception in REST Response

**Comment by planetf1** [comment]
Agree @odttlnt . Whilst the last error is reporting the gradle daemon has gone away this seems consequential. There are also some dependency warnings (issue already open) but they shouldn't affect results. The actual failure is as you mentioned -- something bad about that guid. I do not know why, perhaps the guid isn't found. Am also currently seeing an issue in CTS, but too early to see if related. I think we do have some timing issues in the code, which could be a factor.

**Comment by planetf1** [comment]
See #6450

**Comment by planetf1** [comment]
I think the build fix has resolved your issue. built cleanly. I've just merged another PR and have updated this one, which we can merge if ok :-)

**Pull request merged**
