### PR TITLE
Dependabot 202104b (April 2021 - Spring)

### PR DESCRIPTION
**Pull request by planetf1**
Fixes: #4441 

Updates all spring dependencies to current versions (though tomcat left at 9.x codestream due to issues)

### CODE REVIEW

**Comment by planetf1** [comment]
Current failure is
```
An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.boot.web.embedded.tomcat.SslConnectorCustomizer.configureSsl(SslConnectorCustomizer.java:70)

The following method did not exist:

    'void org.apache.coyote.http11.AbstractHttp11JsseProtocol.setSslProtocol(java.lang.String)'

The method's class, org.apache.coyote.http11.AbstractHttp11JsseProtocol, is available from the following locations:

    jar:file:/Users/jonesn/IdeaProjects/egeria.maven/open-metadata-distribution/open-metadata-assemblies/target/egeria-2.9-SNAPSHOT-distribution/egeria-omag-2.9-SNAPSHOT/user-interface/ui-chassis-spring-2.9-SNAPSHOT.jar!/BOOT-INF/lib/tomcat-embed-core-10.0.4.jar!/org/apache/coyote/http11/AbstractHttp11JsseProtocol.class

The class hierarchy was loaded from the following locations:

    org.apache.coyote.http11.AbstractHttp11JsseProtocol: jar:file:/Users/jonesn/IdeaProjects/egeria.maven/open-metadata-distribution/open-metadata-assemblies/target/egeria-2.9-SNAPSHOT-distribution/egeria-omag-2.9-SNAPSHOT/user-interface/ui-chassis-spring-2.9-SNAPSHOT.jar!/BOOT-INF/lib/tomcat-embed-core-10.0.4.jar!/
    org.apache.coyote.http11.AbstractHttp11Protocol: jar:file:/Users/jonesn/IdeaProjects/egeria.maven/open-metadata-distribution/open-metadata-assemblies/target/egeria-2.9-SNAPSHOT-distribution/egeria-omag-2.9-SNAPSHOT/user-interface/ui-chassis-spring-2.9-SNAPSHOT.jar!/BOOT-INF/lib/tomcat-embed-core-10.0.4.jar!/
    org.apache.coyote.AbstractProtocol: jar:file:/Users/jonesn/IdeaProjects/egeria.maven/open-metadata-distribution/open-metadata-assemblies/target/egeria-2.9-SNAPSHOT-distribution/egeria-omag-2.9-SNAPSHOT/user-interface/ui-chassis-spring-2.9-SNAPSHOT.jar!/BOOT-INF/lib/tomcat-embed-core-10.0.4.jar!/


Action:

Correct the classpath of your application so that it contains a single, compatible version of org.apache.coyote.http11.AbstractHttp11JsseProtocol

```
will investigate more tomorrow

**Comment by planetf1** [comment]
@lpalashevski I think I've now addressed the spring updates, with the minor exception of having to leave tomcat at 9.x (albeit latest) due to some missing methods required by spring boot.

I've been able to run through our notebooks ok so have good confidence the server chassis is ok. I've been able to launch the UI but not tested thoroughly.

I can merge whenever you are happy - just waiting on checking the gradle build is good also.

It will be good to get this in and this should then close the remaining dependabot issues

**Review by lpalashevski — APPROVED** [review]

**Comment by lpalashevski** [comment]
> @lpalashevski I think I've now addressed the spring updates, with the minor exception of having to leave tomcat at 9.x (albeit latest) due to some missing methods required by spring boot.
> 
> I've been able to run through our notebooks ok so have good confidence the server chassis is ok. I've been able to launch the UI but not tested thoroughly.
> 
> I can merge whenever you are happy - just waiting on checking the gradle build is good also.
> 
> It will be good to get this in and this should then close the remaining dependabot issues

Looks good. I did local regression test using the changes directly from this PR. I am able to get ti up and running and can confirm that platform works properly after the major spring updates. We can merge this, approved.

**Comment by planetf1** [comment]
Ok will merge. Can do any refinements like to the front end plug-in in a separate pr

**Pull request merged**
