### PR TITLE
Create stale.yml

### PR DESCRIPTION
**Pull request by jmertic**
Config for stale issue app.

### CODE REVIEW

**Comment by cmgrote** [comment]
@jmertic thanks!  Can I just request you to add a license header (following two lines) to the top of the file so it'll pass through the build checks? 🙏 

```
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
```

**Comment by jmertic** [comment]
Done :-)

**Comment by cmgrote** [comment]
Matches what we discussed on the call today, so going ahead and merging...

**Comment by planetf1** [comment]
super :-)

**Pull request merged**
