### PR TITLE
fix Superfluous developer logging at OMAG Server Platform start

### PR DESCRIPTION
**Pull request by bogdan-sava**

### CODE REVIEW

**Comment by bogdan-sava** [comment]
Please see #4324

**Comment by bogdan-sava** [comment]
this is also fix for https://github.com/odpi/egeria/issues/3392

**Review by planetf1 — CHANGES_REQUESTED** [review]
See discussion in #4324

I'd be inclined to skip this change as
 a) The root cause in many ways is the split role of the module affected - being both a library and executable utility. - though this change does address an immediate impact so this is only an observation/preference not a blocking 'no'
 b) The underlaying issue is not fixed by this change as I see it (though not run code) as the default spring server chassis config file has a default log level of INFO

**Comment by bogdan-sava** [comment]
That is not true.
The default is override by application.properties.

**Comment by bogdan-sava** [comment]
The default spring-boot is override by default aplication.properties as we discussed long time ago, but leaves option to setup levels on deploy.

**Comment by planetf1** [comment]
I completely agree with the intent of the change, I just couldn't see how the code change prevented the info messages given what I saw in the default spring file and the logback xml for the 'library'. That being said I have just ran the chassis and as you asserted, the logging is back as we had expected, so good job :-) Sure we can do the split on the library but this does indeed seem to address the immediate logging issue. thanks.

**Pull request merged**
