### PR TITLE
Include Glossary Terms in lineage result

### PR DESCRIPTION
**Pull request by lcpopa**
Signed-off-by: Liviu Popa <liviu-constantin.popa@ing.com>

### CODE REVIEW

**Comment by GuyAckermans** [comment]
Has it been confirmed that we want to display glossary terms as separate nodes in the UI, rather than including them as properties for the columns and tables? This may greatly clutter the screen of the user when viewing end to end lineage

**Comment by lcpopa** [comment]
@GuyAckermans  I do not have that information. Who can provide it ?

**Comment by planetf1** [comment]
Where is the issue that documents this problem or proposal? 

We should be able to track the work we are doing at a broader level than just in PRs. Indeed one issue may require a number of PRs (and even more commits) to complete.

Current process is documented in https://github.com/odpi/egeria/blob/master/developer-resources/Issue-Tracking.md

**Comment by lcpopa** [comment]
#2716

**Comment by lcpopa** [comment]
> On hold awaiting confirmation whether glossary terms should be properties or separate nodes

Confirmation received.

**Comment by lcpopa** [comment]
> On hold awaiting confirmation whether glossary terms should be properties or separate nodes
This was settled. Option to display glossary terms as either nodes or properties will be implemented in a separate issue. At the moment, they will be displayed as nodes

**Pull request merged**
