### PR TITLE
Fix asset catalog bug with java.lang.UnsupportedOperationException 

### PR DESCRIPTION
**Pull request by ruxandraRosu**
UnsupportedOperationException is thrown when there are no glossary terms for the specified criteria, but there are assets matching the criteria.
This is because Collections.emptyList() returns an abstractList that doesn't support add method.
Snippet from exception stacktrace:
java.lang.UnsupportedOperationException: null
	at java.util.AbstractList.add(AbstractList.java:148) ~[na:1.8.0_212]
	at java.util.AbstractList.add(AbstractList.java:108) ~[na:1.8.0_212]
	at java.util.AbstractCollection.addAll(AbstractCollection.java:344) ~[na:1.8.0_212]
	at org.odpi.openmetadata.accessservices.assetcatalog.service.AssetCatalogService.findAssetsBySearchedPropertyValue(AssetCatalogService.java:864) ~[asset-catalog-server-1.1-SNAPSHOT.jar!/:na]
	at org.odpi.openmetadata.accessservices.assetcatalog.server.spring.AssetCatalogEntityResource.searchAssetsFirstLevel(AssetCatalogEntityResource.java:288) ~[asset-catalog-spring-1.1-SNAPSHOT.jar!/:na]
	at sun.reflect.GeneratedMethodAccessor202.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]

Signed-off-by: ruxandraRosu <ruxandra-gabriela.rosu@ing.com>

### CODE REVIEW

**Comment by planetf1** [comment]
Note - the Sonar scan being run against the PR is running a javascript check on current code.
It had previously been disabled but it appears the recent build changes have reintroduced it.
The bugs reported look genuine, but as the profile differs from daily builds we'll see a sawtooth on our analysis - so I propose to get it disabled again.

We will need to address the backlog sometime.
I've raised #1748 specifically on the UI code as the first of those could lead to unanticipated result.

**Comment by planetf1** [comment]
Added notes to https://github.com/odpi/egeria/issues/1652 - expect to see this check removed.

**Comment by danielaotelea** [comment]
Hi,

I have done a lot of changes on the Asset Catalog OMAS. A new PR is opened for that: https://github.com/odpi/egeria/pull/1761
Please take a look on that and let me know if the bug is still present.

**Comment by ruxandraRosu** [comment]
Closing this PR as a result of refactoring in above mentioned PR

**Pull request closed without merging**
