### PR TITLE
Asset catalog omas

### PR DESCRIPTION
**Pull request by danielaotelea**

### CODE REVIEW

**Comment by planetf1** [comment]
Noting this PR has been open a while -- there are conflicts that need resolving @danielaotelea - can you update then we can continue the review?

**Comment by danielaotelea** [comment]
Hi! Yes, sure. I will create a new PR for these changes, I will check what else is needed to solve the conflicts. Thanks for review.

**Comment by danielaotelea** [comment]
Pull Request updated. Can you take a look on it, please?

**Comment by bogdan-sava** [comment]
The calls were removed.
I'll merge it. I need the fixes from this pull request

**Pull request merged**
