### PR TITLE
Add support for ARM64 Image Build

### PR DESCRIPTION
**Pull request by tcnt**
Signed-off-by: Theo Thomas <tcn.thomas@googlemail.com>

# Description

Removed building images using Maven.
Building Images is now done using Docker directly in the workflow.
Using docker directly enables us to build for multiple architectures.
This is the first step related to https://github.com/odpi/egeria/issues/2391  to enable the use of ARM64 images

Fixes # (issue)

# How Has This Been Tested?

Building the images for AMD64/ARM64 (Raspberry PI) on my own Docker repo.
Tested lab exercises on Kubernetes Cluster on Raspberry PI using images from my own Docker Repo.

# Any additional notes for reviewers?

### CODE REVIEW

**Comment by tcnt** [comment]
@planetf1 
In egeria-ui and egeria-react-ui I see that for release only version is used for tag and for master/main latest and version is used in the tag.

In the release workflow for egeria  always the latest and version is used as tag.
As far as I could see this is similar to what we used when using maven for docker build.
Is this done on purpose in the release for egeria or should it be aligned with the other 2 repos?

**Comment by planetf1** [comment]
> @planetf1 In egeria-ui and egeria-react-ui I see that for release only version is used for tag and for master/main latest and version is used in the tag.

egeria-ui doesn't have a release workflow currently, so the merge build uses ver+latest for main, and ver for !main
The same applies to egeria-react-ui


> In the release workflow for egeria always the latest and version is used as tag. As far as I could see this is similar to what we used when using maven for docker build. Is this done on purpose in the release for egeria or should it be aligned with the other 2 repos?

Egeria has a specific release workflow -- so the decision I took there was the build the docker image as part of that process.
Therefore the merge build only builds for main

Ideally we'd push pre-release images to a staging area, or with an alternate tag automatically to facilitate testing - but that requires more steps.

I would go with the same approach to tags for this PR on the architecture -- but we can certainly discuss improvements to the overall release process in another issue or PR as needed?

**Comment by planetf1** [comment]
Thanks for proposing the change!

**Review by planetf1 — APPROVED** [review]
Reviewed and approved

These changes look good for adding the arm v8 architecture alongside intel/amd 64. 
This also simplifies the build by no longer being dependent on the spotify docker plugin

In a future PR we can provide some docs on rebuilding the docker image to help others incorporate into their CI/CD process, but it makes sense to validate the process first.

Inspected, conditions look good, but will merge and will check build output

**Pull request merged**
