### PR TITLE
Cut-over 2.7 release types to a new extensible master

### PR DESCRIPTION
**Pull request by cmgrote**

### CODE REVIEW

**Comment by cmgrote** [comment]
@mandy-chessell if you can have a quick look and confirm I did this correctly?

Hoping it was as simple as what I did here (just created a new class with the `2_7` name that's a copy of the existing `OpenMetadataTypesArchive`, and then changed the existing `OpenMetadataTypesArchive` to build its original types using the `2_7` class as its previousTypes) (?)

**Comment by cmgrote** [comment]
Looks like this is already done now via #4860 -- closing

**Comment by mandy-chessell** [comment]
Sorry @cmgrote I did not see that you had done this already - if it is any consolation, you commit was completely correct :)

**Comment by cmgrote** [comment]
No worries -- took a matter of seconds to make the change and at least I can be confident of doing it properly next time should the need arise!

**Pull request closed without merging**
