### PR TITLE
# Fix incorrect request paths

### PR DESCRIPTION
**Pull request by immmus**
Signed-off-by: immmus <fonto.trg@gmail.com>

### CODE REVIEW

**Comment by planetf1** [comment]
The grade build is failing after the version bump. It is not due to this pr. I have now disabled the mandatory nature of the check and will look at resolving. . The best push or update should be fine. Apologies

**Comment by immmus** [comment]
@planetf1 @mandy-chessell @davidradl  Hi! Can I ask for this small fix to be included in 2.2 ??

**Comment by planetf1** [comment]
Hi @immmus generally once branched we wouldn't add anything unless it was causing a regression or serious issue.

I haven't started testing or the release cycle for 2.2 yet (had a few build issues) so technically it's minimal impact if needed so I'm ok to include if @davidradl @mandy-chessell are ok with it and we agree today.

**Comment by immmus** [comment]
> Hi @immmus generally once branched we wouldn't add anything unless it was causing a regression or serious issue.
> 
> I haven't started testing or the release cycle for 2.2 yet (had a few build issues) so technically it's minimal impact if needed so I'm ok to include if @davidradl @mandy-chessell are ok with it and we agree today.

Thank you.

**Comment by immmus** [comment]
@davidradl Would you answering on my request?;)

**Comment by davidradl** [comment]
@immmus I hope to look at this tomorrow

**Review by davidradl — APPROVED** [review]

**Comment by davidradl** [comment]
> @immmus I hope to look at this tomorrow

@planetf1 asked me to look at this today for the release.

**Comment by immmus** [comment]
> > @immmus I hope to look at this tomorrow
> 
> @planetf1 asked me to look at this today for the release.

Thank you @planetf1 and @davidradl

**Review by planetf1 — APPROVED** [review]

**Comment by planetf1** [comment]
From inspection (but not with detailed knowledge of this area) the fix appears to address a typo in the request path (thanks!)

I've added this fix to the 2.2 PR for building which will be merged shortly

**Comment by planetf1** [comment]
There are no usages of this code that I could see (application or test case). Therefore it is safe to merge - even if there are other issues in asset owner.

**Pull request merged**
