### PR TITLE
DO NOT MERGE - Dummy to allow clm runs

### PR DESCRIPTION
**Pull request by planetf1**
Creating dummy pull request to allow 'CLM' runs to be kicked off by posting 'run-clm' in this PR

CLM runs should run periodically, and against any PR, but they appear to run against master only -- but have to be initiated from another pr.

Opening this dummy to allow a mechanism for running clm on request, until the Linux foundation build team are able to address/clarify expected behaviour.

Signed-off-by: Nigel Jones <nigel.l.jones+git@gmail.com>

### CODE REVIEW

**Comment by planetf1** [comment]
run-clm

**Comment by schannamallu** [comment]
retest this please

**Comment by planetf1** [comment]
run-clm

**Comment by planetf1** [comment]
run-clm

**Comment by planetf1** [comment]
run-clm

**Comment by planetf1** [comment]
run-clm

**Comment by planetf1** [comment]
This is now running weekly ok. See https://jenkins.odpi.org/view/CLM/job/odpi-egeria-maven-clm-master/
I think therefore this PR has served it's use and we can close.

**Pull request closed without merging**
