### PR TITLE
Add event processor between local repository and local OMASs (#1336)

### PR DESCRIPTION
**Pull request by mandy-chessell**
Signed-off-by: Mandy Chessell <mandy_chessell@uk.ibm.com>

### CODE REVIEW

**Comment by mandy-chessell** [comment]
recheck

**Comment by mandy-chessell** [comment]
recheck

**Comment by mandy-chessell** [comment]
recheck

**Comment by mandy-chessell** [comment]
recheck

**Comment by schannamallu** [comment]
recheck

**Comment by schannamallu** [comment]
recheck

**Comment by schannamallu** [comment]
recheck

**Comment by schannamallu** [comment]
recheck

**Comment by schannamallu** [comment]
recheck

**Comment by schannamallu** [comment]
recheck

**Comment by schannamallu** [comment]
recheck

**Comment by schannamallu** [comment]
recheck

**Comment by schannamallu** [comment]
recheck

**Comment by schannamallu** [comment]
recheck

**Pull request merged**
