### PR TITLE
Revert "Revert "Remove Zuul Module #4549 #3795""

### PR DESCRIPTION
**Pull request by sarbull**
Reverts odpi/egeria#4924

### CODE REVIEW

**Comment by planetf1** [comment]
We should wait until the docker compose change is also done, as noted in the zuul issue

**Review by planetf1 — CHANGES_REQUESTED** [review]
As per original issue, next change is to ensure compose works, then we can flip the switch without breakage.

**Comment by lpalashevski** [comment]
> As per original issue, next change is to ensure compose works, then we can flip the switch without breakage.

Noted. Waiting on update from your side.

**Comment by planetf1** [comment]
Once https://github.com/odpi/egeria/pull/4936 is reviewed and merged I think we're good to go with this one
(and will need to then retest k8s & compose just in case)

Given we're close to branching we may wish to hold off on the zuul removal until after the release, though I am ok with going ahead if you prefer. I would leave spring dependencies as is though

**Pull request merged**
