### PR TITLE
Correct presentation server build to work on Windows

### LINKED ISSUE #3778: Build of the project Presentation server is broken on Windows platform.
Build of the project Presentation server is broken on Windows platform.

[INFO] ----------------< org.odpi.egeria:presentation-server >-----------------
[INFO] Building Egeria Presentation Server 2.4-SNAPSHOT               [295/334]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M3:display-info (display-info) @ presentation-server ---
[INFO] Maven Version: 3.6.1
[INFO] JDK Version: 1.8.0_241 normalized as: 1.8.0-241
[INFO] OS Info: Arch: amd64 Family: windows Name: windows 10 Version: 10.0
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-versions) @ presentation-server ---
[INFO]
[INFO] --- apache-rat-plugin:0.13:check (rat-check) @ presentation-server ---
[INFO] RAT will not execute since it is configured to be skipped via system property 'rat.skip'.
[INFO]
[INFO] --- frontend-maven-plugin:1.10.2:install-node-and-npm (install node and npm) @ presentation-server ---
[INFO] Installing node version v12.16.0
[INFO] Copying node binary from C:\Users\YEVGENIYMarchenko\.m2\repositoryEgeria\com\github\eirslett\node\12.16.0\node-12.16.0-win-x64.exe to C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node\node.exe
[INFO] Installed node locally.
[INFO] Installing npm version 6.14.5
[INFO] Unpacking C:\Users\YEVGENIYMarchenko\.m2\repositoryEgeria\com\github\eirslett\npm\6.14.5\npm-6.14.5.tar.gz into C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node\node_modules
[INFO] Installed npm locally.
[INFO]
[INFO] --- frontend-maven-plugin:1.10.2:npm (npm-install) @ presentation-server ---
[INFO] Running 'npm install --prefix .' in C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\parser -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\@babel\parser\bin\babel-parser.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\acorn -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\acorn\bin\acorn
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\ansi-html -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\ansi-html\bin\ansi-html
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\atob -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\atob\bin\atob.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\cssesc -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\cssesc\bin\cssesc
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\esparse -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\esprima\bin\esparse.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\esvalidate -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\esprima\bin\esvalidate.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\he -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\he\bin\he
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\in-install -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\in-publish\in-install.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\not-in-publish -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\in-publish\not-in-publish.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\in-publish -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\in-publish\in-publish.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\not-in-install -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\in-publish\not-in-install.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\is-ci -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\is-ci\bin.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\jsesc -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\jsesc\bin\jsesc
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\loose-envify -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\loose-envify\cli.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\miller-rabin -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\miller-rabin\bin\miller-rabin
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\mime -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\mime\cli.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\json5 -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\json5\lib\cli.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\mkdirp -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\mkdirp\bin\cmd.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\browserslist -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\browserslist\cli.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\nopt -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\nopt\bin\nopt.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\errno -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\errno\cli.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\regjsparser -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\regjsparser\bin\parser
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\import-local-fixture -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\import-local\fixtures\cli.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\dsv2dsv -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\d3-dsv\bin\dsv2dsv
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\dsv2json -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\d3-dsv\bin\dsv2json
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\csv2json -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\d3-dsv\bin\dsv2json
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\tsv2csv -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\d3-dsv\bin\dsv2dsv
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\csv2tsv -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\d3-dsv\bin\dsv2dsv
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\tsv2json -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\d3-dsv\bin\dsv2json
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\json2dsv -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\d3-dsv\bin\json2dsv
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\json2csv -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\d3-dsv\bin\json2dsv
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\json2tsv -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\d3-dsv\bin\json2dsv
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\semver -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\semver\bin\semver
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\sha.js -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\sha.js\bin.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\js-yaml -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\js-yaml\bin\js-yaml.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\strip-indent -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\strip-indent\cli.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\rc -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\rc\cli.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\terser -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\terser\bin\terser
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\multicast-dns -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\multicast-dns\cli.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\nodetouch -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\touch\bin\nodetouch.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\tree-kill -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\tree-kill\cli.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\sshpk-conv -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\sshpk\bin\sshpk-conv
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\sshpk-sign -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\sshpk\bin\sshpk-sign
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\sshpk-verify -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\sshpk\bin\sshpk-verify
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\uglifyjs -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\uglify-js\bin\uglifyjs
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\html-minifier -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\html-minifier\cli.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\uuid -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\uuid\bin\uuid
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\which -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\which\bin\which
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\rimraf -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\rimraf\bin.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node-gyp -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\node-gyp\bin\node-gyp.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\sassgraph -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\sass-graph\bin\sassgraph
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\concurrently -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\concurrently\bin\concurrently.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\eslint -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\eslint\bin\eslint.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node-sass -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\node-sass\bin\node-sass
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\nodemon -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\nodemon\bin\nodemon.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\webpack -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\webpack\bin\webpack.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\webpack-cli -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\webpack-cli\bin\cli.js
[INFO] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\webpack-dev-server -> C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\webpack-dev-server\bin\webpack-dev-server.js
[INFO]
[INFO] > node-sass@4.14.1 install C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\node-sass
[INFO] > node scripts/install.js
[INFO]
[INFO] Cached binary found at C:\Users\YEVGENIYMarchenko\AppData\Roaming\npm-cache\node-sass\4.14.1\win32-x64-72_binding.node
[INFO]
[INFO] > core-js@2.6.11 postinstall C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\core-js
[INFO] > node -e "try{require('./postinstall')}catch(e){}"
[INFO]
[INFO] Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
[INFO]
[INFO] The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
[INFO] > https://opencollective.com/core-js
[INFO] > https://www.patreon.com/zloirock
[INFO]
[INFO] Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
[INFO]
[INFO]
[INFO] > core-js-pure@3.6.5 postinstall C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\core-js-pure
[INFO] > node -e "try{require('./postinstall')}catch(e){}"
[INFO]
[INFO]
[INFO] > node-sass@4.14.1 postinstall C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\node-sass
[INFO] > node scripts/build.js
[INFO]
[INFO] Binary found at C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\node-sass\vendor\win32-x64-72\binding.node
[INFO] Testing binary
[INFO] Binary is fine
[INFO]
[INFO] > nodemon@1.19.4 postinstall C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\nodemon
[INFO] > node bin/postinstall || exit 0
[INFO]
[**INFO] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\watchpack\node_modules\fsevents):
[INFO] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\watchpack\node_modules\fsevents):added 1357 packages from 655 contributors in 63.469s
[INFO] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
[INFO] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
[INFO] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})**
[INFO]
[INFO]
[INFO] --- frontend-maven-plugin:1.10.2:webpack (webpack-build) @ presentation-server ---
[INFO] Running 'webpack.js --mode development --devtool inline-source-map' in C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs
[INFO] clean-webpack-plugin: C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\dist has been removed.
[INFO] Hash: 4757f81aac0f5784c7df
[INFO] Version: webpack 4.42.0
[INFO] Time: 1601ms
[INFO] Built at: 10/06/2020 2:51:11 AM
[INFO]       Asset       Size  Chunks             Chunk Names
[INFO]   bundle.js    913 KiB    main  [emitted]  main
[INFO] favicon.ico   43.6 KiB          [emitted]
[INFO]  index.html  512 bytes          [emitted]
[INFO] Entrypoint main = bundle.js
[INFO] [0] multi babel-polyfill ./src/client/index.js 40 bytes {main} [built]
[INFO] [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {main} [built]
[INFO] [./src/client/index.js] 4.76 KiB {main} [built] [failed] [1 error]
[INFO]     + 331 hidden modules
[INFO]
**[INFO] ERROR in ./src/client/index.js
[INFO] Module build failed (from ./node_modules/babel-loader/lib/index.js):
[INFO] BrowserslistError: [BABEL] C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\src\client\index.js: Unknown browser query `basedir=$(dirname "$(echo "$0" | sed -e 's`. Maybe you are using old Browserslist or made typo in query. (While processing: "C:\\dev\\egeria\\git\\egeria24\\egeria\\open-metadata-implementation\\user-interfaces\\presentation-server\\nodejs\\node_modules\\@babel\\preset-env\\lib\\index.js")**
[INFO]     at unknownQuery (C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\browserslist\index.js:285:10)
[INFO]     at C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\browserslist\index.js:372:11
[INFO]     at Array.reduce (<anonymous>)
[INFO]     at resolve (C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\browserslist\index.js:318:18)
[INFO]     at browserslist (C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\browserslist\index.js:443:21)
[INFO]     at getTargets (C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\@babel\helper-compilation-targets\lib\index.js:199:48)
[INFO]     at C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\@babel\preset-env\lib\index.js:247:57
[INFO]     at C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\@babel\helper-plugin-utils\lib\index.js:19:12
[INFO]     at C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\@babel\core\lib\config\full.js:199:14
[INFO]     at Generator.next (<anonymous>)
[INFO]     at Function.<anonymous> (C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\@babel\core\lib\gensync-utils\async.js:26:3)
[INFO]     at Generator.next (<anonymous>)
[INFO]     at step (C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\gensync\index.js:254:32)
[INFO]     at evaluateAsync (C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\gensync\index.js:284:5)
[INFO]     at Function.errback (C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\gensync\index.js:108:7)
[INFO]     at errback (C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\@babel\core\lib\gensync-utils\async.js:70:18)
[INFO]     at async (C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\gensync\index.js:183:31)
[INFO]     at onFirstPause (C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\gensync\index.js:209:13)
[INFO]     at Generator.next (<anonymous>)
[INFO]     at cachedFunction (C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\@babel\core\lib\config\caching.js:68:46)
[INFO]     at cachedFunction.next (<anonymous>)
[INFO]     at loadPresetDescriptor (C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\@babel\core\lib\config\full.js:292:43)
[INFO]     at loadPresetDescriptor.next (<anonymous>)
[INFO]     at recurseDescriptors (C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\@babel\core\lib\config\full.js:107:30)
[INFO]     at recurseDescriptors.next (<anonymous>)
[INFO]     at loadFullConfig (C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\@babel\core\lib\config\full.js:142:6)
[INFO]     at loadFullConfig.next (<anonymous>)
[INFO]     at Function.transform (C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\@babel\core\lib\transform.js:25:45)
[INFO]     at transform.next (<anonymous>)
[INFO]     at step (C:\dev\egeria\git\egeria24\egeria\open-metadata-implementation\user-interfaces\presentation-server\nodejs\node_modules\gensync\index.js:262:25)
[INFO]  @ multi babel-polyfill ./src/client/index.js main[1]
[INFO] Child html-webpack-plugin for "index.html":
[INFO]      1 asset
[INFO]     Entrypoint undefined = index.html
[INFO]     [./node_modules/html-webpack-plugin/lib/loader.js!./public/index.html] 635 bytes {0} [built]
[INFO]     [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
[INFO]     [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
[INFO]         + 1 hidden module
[INFO] ------------------------------------------------------------------------

### PR DESCRIPTION
**Pull request by planetf1**
Fixes #3778 

 - removes use of '--prefix' when installing npm packages (the current directory is already correctly set so it's unnecessary and was causing what appears to be a bug)
 - updates npm/node to current LTS versions (minor update)
 - ensures node/npm executables are kept in a seperate folder to keep the build structure clean and ensure build can be rerun

These problems primarily impacted windows, but with fix work on macOS too

### CODE REVIEW

**Comment by davidradl** [comment]
@planetf1 Looks good. I have not tested. The only thing I would query is "target/tools" as the installation folder, is there a reason for using tools. Can we use UserInterfaces instead? Or is there some precedent/reason to use tools.

**Comment by planetf1** [comment]
> @planetf1 Looks good. I have not tested. The only thing I would query is "target/tools" as the installation folder, is there a reason for using tools. Can we use UserInterfaces instead? Or is there some precedent/reason to use tools.

This directory is relative to the module - so it is already under open-metadata-implementation/user-interfaces/presentation-server

Generally speaking it's good practice to keep generated files (which effectively these are) under 'target'. With node generally though it's more tricky a by default it tends to add node_modules to the same dir as the package.json - so I've not done anything with that here. Just the 'npm' and 'node' executable packages which are downloaded at the beginning of the build for this module. 

So I could put under target - but there will/may be other things there too. Indeed as you'll see in a commented out section of the pom, we should be creating other things to go into the maven artifact, so I wanted some qualifier at least I could easily exclude... and so used tools.

Hope that explains it :-)

**Comment by davidradl** [comment]
> > @planetf1 Looks good. I have not tested. The only thing I would query is "target/tools" as the installation folder, is there a reason for using tools. Can we use UserInterfaces instead? Or is there some precedent/reason to use tools.
> 
> This directory is relative to the module - so it is already under open-metadata-implementation/user-interfaces/presentation-server
> 
> Generally speaking it's good practice to keep generated files (which effectively these are) under 'target'. With node generally though it's more tricky a by default it tends to add node_modules to the same dir as the package.json - so I've not done anything with that here. Just the 'npm' and 'node' executable packages which are downloaded at the beginning of the build for this module.
> 
> So I could put under target - but there will/may be other things there too. Indeed as you'll see in a commented out section of the pom, we should be creating other things to go into the maven artifact, so I wanted some qualifier at least I could easily exclude... and so used tools.
> 
> Hope that explains it :-)

Hi Nigel, Understood. Tools does not seem right, maybe build or deploy?

**Comment by planetf1** [comment]
I think all those names have their own issues. 'build' could get confused with the default output directory used by gradle by default, and 'deploy' has a particular meaning in maven!. The word-space is so full. I think avoiding them mingling with source is important. 'bin' was my first choice. I think leave as is.

**Pull request merged**
