### PR TITLE
Fixes LocalConnector validations and considers type version in CTS type compares

### LINKED ISSUE #2356: CTS failures after typedef version changes & fixes
In Release 1.2 I saw
 - 4 CTS failures for the graph repo (all related to the way deletes were handled - subsequently resolved in master)
 - 0 failures for the in-mem repo

However the current master is showing more failures. For example inmem currently shows:
```
Date of conformance test:          2020-01-03T18:28:48.861+0000
Number of tests that were run:     4495
Number of tests that failed:       445
Number of tests that were skipped: 0
```

cc: @grahamwallis @cmgrote @mandy-chessell 

We likely need to resolve this before cutting the 1.3 release.

### PR DESCRIPTION
**Pull request by grahamwallis**
Fixes #2356

### CODE REVIEW

**Comment by planetf1** [comment]
See comment above, but propose we merge this now in any case.

**Comment by planetf1** [comment]
I will do the 1.3 backport.

**Comment by cmgrote** [comment]
Looks good against IGC connector:

```
=======================================
 Open Metadata Conformance Test Report
=======================================
 ... contacting conformance suite server: cts (http://localhost:8080)

Conformance report from server:  cts

Number of tests: 582
Number of tests passed: 582
Number of tests failed: 0
Number of tests skipped: 0

Congratulations, technology under test is conformant
```

**Comment by grahamwallis** [comment]
With regard to the question "when the typedef versions differ, what checks should be done. In theory we would expect compatible changes in a later version (ie additional attributes etc)? Does that matter?" I did start to implement a 'compatibility check' method but quickly realised that it would be a much bigger piece of work - and really needs to be checked when the type update is first made. For now I have implemented a check that says "if version is the same, the type must match exactly, otherwise it is not checked".

**Comment by planetf1** [comment]
See https://github.com/odpi/egeria/pull/2385/commits for 1.3

**Comment by planetf1** [comment]
And yes, when I thought about it - agreed, it's non trivial

**Pull request merged**
