### PR TITLE
[jdbc-connector] Add digital resource jdbc connector - initial commit

### PR DESCRIPTION
**Pull request by lcpopa**
Signed-off-by: Liviu Popa <liviu-constantin.popa@ing.com>

New digital resource jdbc connector

## Description

Connector that uses exclusively the jdbc interface

## Related Issue(s)

Issue soon to be created

## Testing

Tested with the cataloging jdbc connector (soon to be commited)

### CODE REVIEW

**Review by planetf1 — CHANGES_REQUESTED** [review]
I think it would be preferable to have this connector in a separate repository from core egeria. For example egeria-database-connectors (or a new one if preferred)

We have generally been moving connectors out to other repositories since
 - we keep the core focused on essential components - easier to maintain, fix, quicker to build etc
  - make it easier for new people to work on development of new connectors - more focus
  - clearly seperates out the ci/cd aspects. Well defined dependency, well defined deliverable - and a process somewhat different to core egeria (just building a connector)
   - new repo can also focus on tests specific to this connector rather than adding time, lack of clarity to core egeria

**Comment by planetf1** [comment]
I think we agreed we needed to talk about it more - but then our calls stopped...

I did ping @lpalashevski and thought the idea was to go into a diff repo?

**Comment by lpalashevski** [comment]
> I think we agreed we needed to talk about it more - but then our calls stopped...
> 
> I did ping @lpalashevski and thought the idea was to go into a diff repo?

This is correct, thanks Nigel. Internal miss-communication from my side. We will move it as we agreed and discuss the structure of the new repo as we go. Also opening new issue soon as promised.

**Comment by lcpopa** [comment]
Thank you for clarifying, will cancel this PR and move the code to https://github.com/odpi/egeria-database-connectors

**Comment by lcpopa** [comment]
Closed as agreed

**Pull request closed without merging**
