### PR TITLE
Tutorials

### PR DESCRIPTION
**Pull request by cmgrote**
- minor formatting updates
- fixes a couple formatting / instruction issues (commands without newlines between, `servers` instead of `server`, etc)
- adds startup tutorial for in-memory repo

### CODE REVIEW

**Comment by mandy-chessell** [comment]
Hello Chris,
I am in the middle of writing these tutorials - please do not update as you are not aware of the over all flow.
Mandy

**Comment by cmgrote** [comment]
Ok, sorry!  Just trying to help in case you were flooded...  Should we reject & close this PR?

**Comment by mandy-chessell** [comment]
Probably would be best - I think we are changing the same files and unpicking the conflicts would be time consuming.

**Comment by cmgrote** [comment]
Closing for now -- give me a shout if I can help in the meantime!

**Pull request closed without merging**
