### PR TITLE
Design updates

### PR DESCRIPTION
**Pull request by alexcontini**
@mandy-chessell here is the PR for the design revisions to the site. Just for reference, the test site is here: https://alexcontini.github.io/egeria/

Let me know if there are any issues!

### CODE REVIEW

**Comment by mandy-chessell** [comment]
Thanks Alex ...

The pull request is failing because the commits are not signed.  There are 
also hard coded links to files in your github repository - I added 
comments to show the ones I saw.
I see the image files are included in the pull request.   Is the intention 
to update the links in a second pull request?

There are also changes to some of the markdown files, but not all of them. 
 Some do not seem to have changed the actual content - for example a line 
is deleted and then added with the same content, or a space at the end of 
the line is removed.  I would suggest that these changes are removed from 
the PR.  But there are other changes that seem important.   For example, 
the following lines are added to the open metadata distribution and some 
of the compliance suite readmes:

---
layout: subpage
css: style-sub.css
---

Do we need to make similar changes to all of the markdown files?  (this is 
not a problem - we just need to know what to do)

There is a new file called index.md that has a copy of the top-level 
README.md content plus the following header:

---
layout: homepage
css: style-sub.css
--- 

Do we need to maintain two copies of the content?  Or could the layout 
tags go in the readme?  What is the purpose of each file?

Many thanks for your help.


All the best
Mandy
___________________________________________
Mandy Chessell CBE FREng CEng FBCS
IBM Distinguished Engineer

Master Inventor
Member of the IBM Academy of Technology
Visiting Professor, Department of Computer Science, University of 
Sheffield

Email: mandy_chessell@uk.ibm.com
LinkedIn: http://www.linkedin.com/pub/mandy-chessell/22/897/a49

Assistant: Janet Brooks - jsbrooks12@uk.ibm.com

**Comment by bogdan-sava** [comment]
run-clm

**Comment by alexcontini** [comment]
Hello Mandy,

Sounds good, and sorry for any confusion.

I will sign the commits, sorry about that. As for the rest -


I planned on updating the hard-coded links in another pull request if that
works?


As for the markdown file changes, please ignore all of those updates. You
do not need to update any of those files, and adding
---
layout: subpage
css: style-sub.css
---
was a mistake, sorry about that and please ignore and keep the markdown
files the same as you have.



The only edit I had to do was to to add the index.md file as the layout for
that one page is different, and we can't add the -
---
layout: homepage
css: style-sub.css
---
to readme files without breaking it. Is it okay to keep both? (the homepage
of the site defaults to the index.md file instead).


Otherwise I think besides signing the commits that is all? I think I should
create another PR to fix the markdown addition issues. I will cancel my
current one and do that soon,

Alex

**Comment by alexcontini** [comment]
closing this and will open another!

**Pull request closed without merging**
