### PR TITLE
Additional POM cleanup 

### PR DESCRIPTION
**Pull request by planetf1**
See #1173 
 - Removed a few lingering exceptions not addressed in major update
 - checked & left require exceptions for dynamically loaded content in place

### CODE REVIEW

**Comment by schannamallu** [comment]
recheck

**Comment by planetf1** [comment]
recheck

**Comment by planetf1** [comment]
recheck

**Comment by schannamallu** [comment]
recheck

**Comment by schannamallu** [comment]
recheck

**Pull request merged**
