### PR TITLE
#5325 Split open metadata types utility off into new module to avoid …

### PR DESCRIPTION
**Pull request by planetf1**
…slf4j implementation contamination

Signed-off-by: Nigel Jones <nigel.l.jones+git@gmail.com>

This PR aims to resolve an issue whereby we contaminate our dependency chain by including a library with a log4J binding - something that should be managed at the application level, not a library, which should use only an API. The problem is that this artifact is both a library and an application, which is problematic (and has already been addressed elsewhere). This has led to ping-pong behaviour in addressing logback issues as one behaviour becomes more important than another & vice versa. This PR should enable a permanent fix.

The affected module is 'open-metadata-types' which is included transitively in much of egeria.

The fix involves
 - creation of a new module 'open-metadata-types-utility' as a peer of open-metadata-types. (we could split into a hierarchy, but this involves more refactoring plus I wanted a simple way to not change the name of the existing artifact)
 - the main() from open-metadata-types moved over to the new module, complete with the logback configuration/processing/config
  - allowing public access to the archive writer & constructor (other more involved approaches could avoid this if desired)
  - updating of assembly to include new utility (it is now called open-metadata-types-utility - but that seems clearer anyway)
  
I HAVE NOT
 - added any docs (other than a one liner) on the utility
 - attempted to improve the usability of the utility - online help etc.
 
 TBD - testing of behaviour with this fix in place
 
Fixes: #5325

### CODE REVIEW

**Comment by planetf1** [comment]
Example before:
```
[INFO] ----------------< org.odpi.egeria:subject-area-spring >-----------------
[INFO] Building Subject Area OMAS with Spring 2.11-SNAPSHOT           [240/393]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:3.1.2:tree (default-cli) @ subject-area-spring ---
[INFO] org.odpi.egeria:subject-area-spring:jar:2.11-SNAPSHOT
[INFO] +- org.odpi.egeria:subject-area-server:jar:2.11-SNAPSHOT:compile
[INFO] |  +- org.odpi.egeria:admin-services-api:jar:2.11-SNAPSHOT:compile
[INFO] |  +- org.odpi.egeria:admin-services-registration:jar:2.11-SNAPSHOT:compile
[INFO] |  +- org.odpi.egeria:audit-log-framework:jar:2.11-SNAPSHOT:compile
[INFO] |  +- org.odpi.egeria:open-connector-framework:jar:2.11-SNAPSHOT:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO] |  +- org.odpi.egeria:open-metadata-types:jar:2.11-SNAPSHOT:compile
[INFO] |  |  +- org.odpi.egeria:repository-services-archive-utilities:jar:2.11-SNAPSHOT:compile
[INFO] |  |  |  +- org.odpi.egeria:open-metadata-archive-file-connector:jar:2.11-SNAPSHOT:compile
[INFO] |  |  |  \- commons-io:commons-io:jar:2.9.0:compile
[INFO] |  |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] |  |  \- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO] |  +- org.odpi.egeria:multi-tenant:jar:2.11-SNAPSHOT:compile
[INFO] |  |  +- org.odpi.egeria:metadata-security-server:jar:2.11-SNAPSHOT:compile
[INFO] |  |  |  +- org.odpi.egeria:metadata-security-apis:jar:2.11-SNAPSHOT:compile
[INFO] |  |  |  \- org.odpi.egeria:metadata-security-connectors:jar:2.11-SNAPSHOT:compile
[INFO] |  |  +- org.odpi.egeria:platform-services-api:jar:2.11-SNAPSHOT:compile
[INFO] |  |  +- org.odpi.egeria:ocf-metadata-handlers:jar:2.11-SNAPSHOT:compile
[INFO] |  |  |  \- org.odpi.egeria:ocf-metadata-api:jar:2.11-SNAPSHOT:compile
[INFO] |  |  +- org.odpi.egeria:engine-host-services-registration:jar:2.11-SNAPSHOT:compile
[INFO] |  |  |  +- org.odpi.egeria:governance-action-framework:jar:2.11-SNAPSHOT:compile
[INFO] |  |  |  +- org.odpi.egeria:governance-engine-api:jar:2.11-SNAPSHOT:compile
[INFO] |  |  |  +- org.odpi.egeria:governance-engine-client:jar:2.11-SNAPSHOT:compile
[INFO] |  |  |  |  +- org.odpi.egeria:governance-engine-topic-connectors:jar:2.11-SNAPSHOT:compile
[INFO] |  |  |  |  \- org.odpi.egeria:ocf-metadata-client:jar:2.11-SNAPSHOT:compile
[INFO] |  |  |  \- org.odpi.egeria:engine-host-services-api:jar:2.11-SNAPSHOT:compile
[INFO] |  |  \- org.odpi.egeria:integration-daemon-services-registration:jar:2.11-SNAPSHOT:compile
[INFO] |  |     \- org.odpi.egeria:integration-daemon-services-api:jar:2.11-SNAPSHOT:compile
[INFO] |  +- org.odpi.egeria:repository-handler:jar:2.11-SNAPSHOT:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.12.3:compile
[INFO] |  +- org.reflections:reflections:jar:0.9.12:compile
[INFO] |  |  \- org.javassist:javassist:jar:3.28.0-GA:compile
[INFO] |  +- org.apache.commons:commons-collections4:jar:4.4:compile
[INFO] |  \- org.odpi.egeria:ffdc-services:jar:2.11-SNAPSHOT:compile
[INFO] |     +- org.odpi.egeria:rest-client-connectors-api:jar:2.11-SNAPSHOT:compile
[INFO] |     +- org.odpi.egeria:rest-client-factory:jar:2.11-SNAPSHOT:compile
[INFO] |     +- org.odpi.egeria:spring-rest-client-connector:jar:2.11-SNAPSHOT:compile
[INFO] |     |  \- org.codehaus.plexus:plexus-utils:jar:3.3.0:compile
[INFO] |     \- org.apache.commons:commons-lang3:jar:3.12.0:compile
[INFO] +- org.odpi.egeria:subject-area-api:jar:2.11-SNAPSHOT:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.12.3:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-core:jar:2.12.3:compile
[INFO] +- org.odpi.egeria:repository-services-apis:jar:2.11-SNAPSHOT:compile
[INFO] +- org.springframework:spring-web:jar:5.3.7:compile
[INFO] |  +- org.springframework:spring-beans:jar:5.3.7:compile
[INFO] |  \- org.springframework:spring-core:jar:5.3.7:compile
[INFO] |     \- org.springframework:spring-jcl:jar:5.3.7:compile
[INFO] +- io.swagger.core.v3:swagger-annotations:jar:2.1.9:compile
[INFO] \- org.slf4j:slf4j-simple:jar:1.7.30:test
```
Note the inclusion of logback libraries via a LIBRARY - open-metadata-types

Behaviour after
```
[INFO] Building Subject Area OMAS with Spring 2.11-SNAPSHOT           [240/394]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:3.1.2:tree (default-cli) @ subject-area-spring ---
[INFO] org.odpi.egeria:subject-area-spring:jar:2.11-SNAPSHOT
[INFO] +- org.odpi.egeria:subject-area-server:jar:2.11-SNAPSHOT:compile
[INFO] |  +- org.odpi.egeria:admin-services-api:jar:2.11-SNAPSHOT:compile
[INFO] |  +- org.odpi.egeria:admin-services-registration:jar:2.11-SNAPSHOT:compile
[INFO] |  +- org.odpi.egeria:audit-log-framework:jar:2.11-SNAPSHOT:compile
[INFO] |  +- org.odpi.egeria:open-connector-framework:jar:2.11-SNAPSHOT:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO] |  +- org.odpi.egeria:open-metadata-types:jar:2.11-SNAPSHOT:compile
[INFO] |  |  \- org.odpi.egeria:repository-services-archive-utilities:jar:2.11-SNAPSHOT:compile
[INFO] |  |     +- org.odpi.egeria:open-metadata-archive-file-connector:jar:2.11-SNAPSHOT:compile
[INFO] |  |     \- commons-io:commons-io:jar:2.9.0:compile
[INFO] |  +- org.odpi.egeria:multi-tenant:jar:2.11-SNAPSHOT:compile
[INFO] |  |  +- org.odpi.egeria:metadata-security-server:jar:2.11-SNAPSHOT:compile
[INFO] |  |  |  +- org.odpi.egeria:metadata-security-apis:jar:2.11-SNAPSHOT:compile
[INFO] |  |  |  \- org.odpi.egeria:metadata-security-connectors:jar:2.11-SNAPSHOT:compile
[INFO] |  |  +- org.odpi.egeria:platform-services-api:jar:2.11-SNAPSHOT:compile
[INFO] |  |  +- org.odpi.egeria:ocf-metadata-handlers:jar:2.11-SNAPSHOT:compile
[INFO] |  |  |  \- org.odpi.egeria:ocf-metadata-api:jar:2.11-SNAPSHOT:compile
[INFO] |  |  +- org.odpi.egeria:engine-host-services-registration:jar:2.11-SNAPSHOT:compile
[INFO] |  |  |  +- org.odpi.egeria:governance-action-framework:jar:2.11-SNAPSHOT:compile
[INFO] |  |  |  +- org.odpi.egeria:governance-engine-api:jar:2.11-SNAPSHOT:compile
[INFO] |  |  |  +- org.odpi.egeria:governance-engine-client:jar:2.11-SNAPSHOT:compile
[INFO] |  |  |  |  +- org.odpi.egeria:governance-engine-topic-connectors:jar:2.11-SNAPSHOT:compile
[INFO] |  |  |  |  \- org.odpi.egeria:ocf-metadata-client:jar:2.11-SNAPSHOT:compile
[INFO] |  |  |  \- org.odpi.egeria:engine-host-services-api:jar:2.11-SNAPSHOT:compile
[INFO] |  |  \- org.odpi.egeria:integration-daemon-services-registration:jar:2.11-SNAPSHOT:compile
[INFO] |  |     \- org.odpi.egeria:integration-daemon-services-api:jar:2.11-SNAPSHOT:compile
[INFO] |  +- org.odpi.egeria:repository-handler:jar:2.11-SNAPSHOT:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.12.3:compile
[INFO] |  +- org.reflections:reflections:jar:0.9.12:compile
[INFO] |  |  \- org.javassist:javassist:jar:3.28.0-GA:compile
[INFO] |  +- org.apache.commons:commons-collections4:jar:4.4:compile
[INFO] |  \- org.odpi.egeria:ffdc-services:jar:2.11-SNAPSHOT:compile
[INFO] |     +- org.odpi.egeria:rest-client-connectors-api:jar:2.11-SNAPSHOT:compile
[INFO] |     +- org.odpi.egeria:rest-client-factory:jar:2.11-SNAPSHOT:compile
[INFO] |     +- org.odpi.egeria:spring-rest-client-connector:jar:2.11-SNAPSHOT:compile
[INFO] |     |  \- org.codehaus.plexus:plexus-utils:jar:3.3.0:compile
[INFO] |     \- org.apache.commons:commons-lang3:jar:3.12.0:compile
[INFO] +- org.odpi.egeria:subject-area-api:jar:2.11-SNAPSHOT:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.12.3:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-core:jar:2.12.3:compile
[INFO] +- org.odpi.egeria:repository-services-apis:jar:2.11-SNAPSHOT:compile
[INFO] +- org.springframework:spring-web:jar:5.3.7:compile
[INFO] |  +- org.springframework:spring-beans:jar:5.3.7:compile
[INFO] |  \- org.springframework:spring-core:jar:5.3.7:compile
[INFO] |     \- org.springframework:spring-jcl:jar:5.3.7:compile
[INFO] +- io.swagger.core.v3:swagger-annotations:jar:2.1.9:compile
[INFO] \- org.slf4j:slf4j-simple:jar:1.7.30:test
```
whilst in our new module -- for the CLI utility - we see logback has been preserved:
```
[INFO] ------------< org.odpi.egeria:open-metadata-types-utility >-------------
[INFO] Building Open Metadata Types Utility 2.11-SNAPSHOT             [374/394]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:3.1.2:tree (default-cli) @ open-metadata-types-utility ---
[INFO] org.odpi.egeria:open-metadata-types-utility:jar:2.11-SNAPSHOT
[INFO] +- org.odpi.egeria:open-metadata-types:jar:2.11-SNAPSHOT:compile
[INFO] |  +- org.odpi.egeria:repository-services-apis:jar:2.11-SNAPSHOT:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.12.3:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.12.3:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.12.3:compile
[INFO] |  |  +- org.odpi.egeria:audit-log-framework:jar:2.11-SNAPSHOT:compile
[INFO] |  |  +- org.odpi.egeria:open-connector-framework:jar:2.11-SNAPSHOT:compile
[INFO] |  |  \- org.apache.commons:commons-collections4:jar:4.4:compile
[INFO] |  \- org.odpi.egeria:repository-services-archive-utilities:jar:2.11-SNAPSHOT:compile
[INFO] |     +- org.odpi.egeria:open-metadata-archive-file-connector:jar:2.11-SNAPSHOT:compile
[INFO] |     \- commons-io:commons-io:jar:2.9.0:compile
[INFO] +- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO] +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] +- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO] \- org.slf4j:slf4j-simple:jar:1.7.30:test
```

What still needs validation is to check the full build output for any other errors suggesting a missing slf4j binding (in an application) or a duplicate binding (caused by a library such as this). Some issues could be caused by fixes after the prior incomplete fix (due to the underlying cause still being present).

.. tbd.

**Comment by planetf1** [comment]
Note: Maven error with the inclusion of the utility project - will correct next week. Meanwhile, comments welcome on the general approach.

**Comment by planetf1** [comment]
After this change
* server chassis & ui chassis start up with no slf4j errors 
* A selection of utilities also work with no errors
* Build logs show only one instance of multiple binding

```
09:50:15,660 [INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ glossary-canonical-model ---
09:50:15,666 [INFO]
09:50:15,666 [INFO] -------------------------------------------------------
09:50:15,666 [INFO]  T E S T S
09:50:15,666 [INFO] -------------------------------------------------------
09:50:15,778 [ERROR] Picked up JAVA_TOOL_OPTIONS: --add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED
09:50:16,225 [INFO] Running org.odpi.openmetadata.archiveutilities.designmodels.owlcanonicalglossarymodel.TestOwlCanonicalGlossar
yModelArchiveBuilder

Model file Name: src/test/resources/EgeriaSampleOntology.json

Retrieving model contents from: src/test/resources/EgeriaSampleOntology.json
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/jonesn/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/or
g/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/jonesn/.m2/repository/org/slf4j/slf4j-simple/1.7.30/slf4j-simple-1.7.30.jar!/org/slf4j/i
mpl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Found 1 glossaries
Found 3 categories
Found 3 concept terms
Found 1object property terms
No resourceSubClassMap
Found 0 literalSubClassMap
Found 2 rangesMap
Found 2 domainsMap
Found 8 is defined by Map
Found 3 members Map
GUIDs map size: 27
09:50:18,425 [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.198 s - in org.odpi.openmetadata.archiveutilities.designmodels.owlcanonicalglossarymodel.TestOwlCanonicalGlossaryModelArchiveBuilder
```

The issue here is that we hav
 - logback-classic/core -- dependencies since this artifact is an executable, so this is needed for normal use
 - slf4j-simple -- included in test scope (as we have tests for this module - but the tests use the jar)
 
 This is very low impact as it only affects one utility, and only when testing, and either binding will work for testing. 
 
 Since we can't exclude a parent from a dependency, we modify the surefire plugin configuration to drop slf4j-simple from the classpath used for testing, which has the same effect. This leaves the utility unmodified for regular useage, using the logback configuration

**Comment by planetf1** [comment]
As an aside, some of these finer details still need attention in the gradle build, which needs to be compared to the results of the maven build. defer to #3370

**Comment by planetf1** [comment]
Build now appears clean.

**Comment by planetf1** [comment]
@bogdan-sava are you good with this fix? I know you had issues with the logging before -- I hope this fixes one of the underlying issues

**Comment by bogdan-sava** [comment]
Looks good!
I'll do a quick test to see the log patterns for the server-chassis.

**Review by bogdan-sava — APPROVED** [review]

**Comment by planetf1** [comment]
Thanks @bogdan. will merge shortly if no objections on developers call.

**Comment by planetf1** [comment]
Review comment in developer call - add library vs executable principle to developer guide

**Comment by planetf1** [comment]
transient network issue causing build failure - close/reopen

**Pull request merged**
