### PR TITLE
Updates to IGC Helm template

### LINKED ISSUE #976: Update IGC proxy configuration in Helm chart
Post-migration of the IGC connector, update the proxy configuration of the Helm chart for IGC to dynamically load the connector jar as part of the initialisation of an otherwise vanilla Egeria (core) container image.

### PR DESCRIPTION
**Pull request by cmgrote**
Updates the IGC Helm template for VDC chart to fix #976:

- Points to static ODPi GitHub repo location for obtaining IGC repository connector (for now)
- Simplifies the IGC template (removes duplicate sections across conditional statements)
- Updates ConfigMap, Values and Proxy Init job to use new parameters of the connector

Note: the updated template will not actually work until a new Egeria (OMAG Server Platform) Docker image has been built and released that uses the new packaging mechanism included in #964.

### CODE REVIEW

**Comment by planetf1** [comment]
Have started a new build of images from master (official builds/id not quite ready yet).

**Comment by cmgrote** [comment]
I tested the contents of this PR locally against a local Docker image built against master, and the PR worked prior to submitting; but please do (/ happy to) re-test once we have the latest images publicly available on Docker Hub 👍

**Comment by planetf1** [comment]
Have hit some issues with building (inc resource, travel etc) but FYI current block is
https://github.com/odpi/egeria/issues/1006

Will try and investigate when time allows, but I think we need to hold off merging this change until the base images are in place

**Comment by cmgrote** [comment]
> Will try and investigate when time allows, but I think we need to hold off merging this change until the base images are in place

That's fine, just be aware that the IGC adapter code is already removed from this repo, so the base images will no longer have any IGC connectivity embedded once built & put into Docker Hub.  (So we should try to merge these very shortly thereafter for continuity of the IGC piece 😉)

**Comment by planetf1** [comment]
I've now made the other nec essary changes so suggest we merge these all together

**Comment by cmgrote** [comment]
@planetf1 I'll let you "orchestrate" the merges, if that works? 😄

**Comment by planetf1** [comment]
Yes, and I'll also deploy/test

**Pull request merged**
