### PR TITLE
Glossary Author FVT #5715

### PR DESCRIPTION
**Pull request by odttlnt**
# Description

Addition of Glossary Author Vie FVTs 

Fixes # 5715

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration. Consider any more risky areas that you need advice on.

# Any additional notes for reviewers?

### CODE REVIEW

**Comment by odttlnt** [comment]
I have added the dependencies to the POM. Now getting a good "clean install".

**Comment by davidradl** [comment]
I am still getting failures when I run mvnclean install locally "[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   CategoryHierarchyIT.testCategoryHierarchy:26 Unexpected exception thrown: org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException: OMAG-COMMON-400-016 An unexpected org.odpi.openmetadata.viewservices.glossaryauthor.services.GlossaryAuthorViewGlossaryRESTServices exception was caught by find for Glossary; error message was OMAG-COMMON-503-001 A client-side exception was received from API call getConfig to OMAG Server serverinmem at https://localhost:10454.  The error message was CLIENT-SIDE-REST-API-CONNECTOR-503-002 A client-side exception org.springframework.web.client.ResourceAccessException was received by method getConfig from API call https://localhost:10454/servers/serverinmem/open-metadata/access-services/subject-area/users/garygeeke/configs/current to server serverinmem on platform https://localhost:10454.  The error message was I/O error on GET request for "https://localhost:10454/servers/serverinmem/open-metadata/access-services/subject-area/users/garygeeke/configs/current": Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty; nested exception is javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[ERROR]   CategoryIT.testCategory:26 Unexpected exception thrown: org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException: OMAG-COMMON-400-016 An unexpected org.odpi.openmetadata.viewservices.glossaryauthor.services.GlossaryAuthorViewGlossaryRESTServices exception was caught by find for Glossary; error message was OMAG-COMMON-503-001 A client-side exception was received from API call getConfig to OMAG Server serverinmem at https://localhost:10454.  The error message was CLIENT-SIDE-REST-API-CONNECTOR-503-002 A client-side exception org.springframework.web.client.ResourceAccessException was received by method getConfig from API call https://localhost:10454/servers/serverinmem/open-metadata/access-services/subject-area/users/garygeeke/configs/current to server serverinmem on platform https://localhost:10454.  The error message was I/O error on GET request for "https://localhost:10454/servers/serverinmem/open-metadata/access-services/subject-area/users/garygeeke/configs/current": Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty; nested exception is javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[ERROR]   EffectiveDatesIT.testEffectiveDates:26 Unexpected exception thrown: org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException: OMAG-COMMON-400-016 An unexpected org.odpi.openmetadata.viewservices.glossaryauthor.services.GlossaryAuthorViewGlossaryRESTServices exception was caught by find for Glossary; error message was OMAG-COMMON-503-001 A client-side exception was received from API call getConfig to OMAG Server serverinmem at https://localhost:10454.  The error message was CLIENT-SIDE-REST-API-CONNECTOR-503-002 A client-side exception org.springframework.web.client.ResourceAccessException was received by method getConfig from API call https://localhost:10454/servers/serverinmem/open-metadata/access-services/subject-area/users/garygeeke/configs/current to server serverinmem on platform https://localhost:10454.  The error message was I/O error on GET request for "https://localhost:10454/servers/serverinmem/open-metadata/access-services/subject-area/users/garygeeke/configs/current": Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty; nested exception is javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[ERROR]   GlossaryIT.testGlossary:25 Unexpected exception thrown: org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException: OMAG-COMMON-400-016 An unexpected org.odpi.openmetadata.viewservices.glossaryauthor.services.GlossaryAuthorViewGlossaryRESTServices exception was caught by find for Glossary; error message was OMAG-COMMON-503-001 A client-side exception was received from API call getConfig to OMAG Server serverinmem at https://localhost:10454.  The error message was CLIENT-SIDE-REST-API-CONNECTOR-503-002 A client-side exception org.springframework.web.client.ResourceAccessException was received by method getConfig from API call https://localhost:10454/servers/serverinmem/open-metadata/access-services/subject-area/users/garygeeke/configs/current to server serverinmem on platform https://localhost:10454.  The error message was I/O error on GET request for "https://localhost:10454/servers/serverinmem/open-metadata/access-services/subject-area/users/garygeeke/configs/current": Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty; nested exception is javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[ERROR]   GraphIT.testGraph:26 Unexpected exception thrown: org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException: OMAG-COMMON-400-016 An unexpected org.odpi.openmetadata.viewservices.glossaryauthor.services.GlossaryAuthorViewGlossaryRESTServices exception was caught by find for Glossary; error message was OMAG-COMMON-503-001 A client-side exception was received from API call getConfig to OMAG Server serverinmem at https://localhost:10454.  The error message was CLIENT-SIDE-REST-API-CONNECTOR-503-002 A client-side exception org.springframework.web.client.ResourceAccessException was received by method getConfig from API call https://localhost:10454/servers/serverinmem/open-metadata/access-services/subject-area/users/garygeeke/configs/current to server serverinmem on platform https://localhost:10454.  The error message was I/O error on GET request for "https://localhost:10454/servers/serverinmem/open-metadata/access-services/subject-area/users/garygeeke/configs/current": Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty; nested exception is javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[ERROR]   ProjectIT.testProject:24 Unexpected exception thrown: org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException: OMAG-COMMON-400-016 An unexpected org.odpi.openmetadata.viewservices.glossaryauthor.services.GlossaryAuthorViewGlossaryRESTServices exception was caught by find for Glossary; error message was OMAG-COMMON-503-001 A client-side exception was received from API call getConfig to OMAG Server serverinmem at https://localhost:10454.  The error message was CLIENT-SIDE-REST-API-CONNECTOR-503-002 A client-side exception org.springframework.web.client.ResourceAccessException was received by method getConfig from API call https://localhost:10454/servers/serverinmem/open-metadata/access-services/subject-area/users/garygeeke/configs/current to server serverinmem on platform https://localhost:10454.  The error message was I/O error on GET request for "https://localhost:10454/servers/serverinmem/open-metadata/access-services/subject-area/users/garygeeke/configs/current": Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty; nested exception is javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[ERROR]   RelationshipsIT.testRelationships:25 Unexpected exception thrown: org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException: OMAG-COMMON-400-016 An unexpected org.odpi.openmetadata.viewservices.glossaryauthor.services.GlossaryAuthorViewGlossaryRESTServices exception was caught by find for Glossary; error message was OMAG-COMMON-503-001 A client-side exception was received from API call getConfig to OMAG Server serverinmem at https://localhost:10454.  The error message was CLIENT-SIDE-REST-API-CONNECTOR-503-002 A client-side exception org.springframework.web.client.ResourceAccessException was received by method getConfig from API call https://localhost:10454/servers/serverinmem/open-metadata/access-services/subject-area/users/garygeeke/configs/current to server serverinmem on platform https://localhost:10454.  The error message was I/O error on GET request for "https://localhost:10454/servers/serverinmem/open-metadata/access-services/subject-area/users/garygeeke/configs/current": Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty; nested exception is javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[ERROR]   SubjectAreaDefinitionCategoryIT.testSubjectAreaDefinitionCategory:25 Unexpected exception thrown: org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException: OMAG-COMMON-400-016 An unexpected org.odpi.openmetadata.viewservices.glossaryauthor.services.GlossaryAuthorViewGlossaryRESTServices exception was caught by find for Glossary; error message was OMAG-COMMON-503-001 A client-side exception was received from API call getConfig to OMAG Server serverinmem at https://localhost:10454.  The error message was CLIENT-SIDE-REST-API-CONNECTOR-503-002 A client-side exception org.springframework.web.client.ResourceAccessException was received by method getConfig from API call https://localhost:10454/servers/serverinmem/open-metadata/access-services/subject-area/users/garygeeke/configs/current to server serverinmem on platform https://localhost:10454.  The error message was I/O error on GET request for "https://localhost:10454/servers/serverinmem/open-metadata/access-services/subject-area/users/garygeeke/configs/current": Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty; nested exception is javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[ERROR]   TermIT.testTerm:26 Unexpected exception thrown: org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException: OMAG-COMMON-400-016 An unexpected org.odpi.openmetadata.viewservices.glossaryauthor.services.GlossaryAuthorViewGlossaryRESTServices exception was caught by find for Glossary; error message was OMAG-COMMON-503-001 A client-side exception was received from API call getConfig to OMAG Server serverinmem at https://localhost:10454.  The error message was CLIENT-SIDE-REST-API-CONNECTOR-503-002 A client-side exception org.springframework.web.client.ResourceAccessException was received by method getConfig from API call https://localhost:10454/servers/serverinmem/open-metadata/access-services/subject-area/users/garygeeke/configs/current to server serverinmem on platform https://localhost:10454.  The error message was I/O error on GET request for "https://localhost:10454/servers/serverinmem/open-metadata/access-services/subject-area/users/garygeeke/configs/current": Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty; nested exception is javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[INFO] 
[ERROR] Tests run: 10, Failures: 9, Errors: 0, Skipped: 0"

**Comment by davidradl** [comment]
I will approve so the workflows run

**Comment by davidradl** [comment]
I have successfully built the pr using mvn clean install. I see the following in the output 
[INFO] Stewardship Action OMAS FVT ........................ SUCCESS [01:03 min]
[INFO] Subject Area OMAS FVT .............................. SUCCESS [43:39 min]
[INFO] OMVS FV and SV Tests ............................... SUCCESS [  0.622 s]
[INFO] Glossary Author OMVS FVT ........................... SUCCESS [01:59 min]
[INFO] Open Metadata Open Types Test Resources ............ SUCCESS [  3.615 s]
[INFO] Open Types Test generator .......................... SUCCESS [ 16.176 s]
[INFO] Open Types Test execution .......................... SUCCESS [01:13 min]

The subject area FVT takes 43 mins the glossary Author I would expect to take longer and takes 2 minutes. It looks like it is being driven and it is 20 times faster! This seems very good news :-) Any ideas why ? Can you confirm this is as you expect please? 
fyi @planetf1

**Comment by davidradl** [comment]
@odttlnt There are some code scanning errors - that are failing the build - should be easy fixes I think/

**Comment by davidradl** [comment]
@planetf1 @odttlnt If this performance is really this good - maybe we should remove the subject area FVt from the build and only run the faster glossary author FVt - which actually drives the same code paths in the Subject Area OMAS as it calls it!

**Comment by odttlnt** [comment]
> @odttlnt There are some code scanning errors - that are failing the build - should be easy fixes I think/

So there are in all 5 errors. The fifth error is for a unused variable. I will correct that. The remaining ones are for some variation of code like termForUniqueQFN2 == null || termForUniqueQFN2.equals("")). Now this same code is there in the SubjectArea FVTs. Wondering if there was some setting in CodeQL that passed that code but is erroring out for this one.

**Comment by planetf1** [comment]
A few minor compiler warnings (I know we have these in many places, but spotted when I tried testing)
```
09:19:11,811 [INFO] Compiling 31 source files to /home/jonesn/src/egeria/open-metadata-test/open-metadata-fvt/view-services-fvt/glossary-author-fvt/target/classes
09:19:12,368 [WARNING] /home/jonesn/src/egeria/open-metadata-test/open-metadata-fvt/view-services-fvt/glossary-author-fvt/src/main/java/org/odpi/openmetadata/viewservices/glossaryauthor/fvt/TermFVT.java:[675,33] unchecked conversion
  required: java.util.Set<java.lang.String>
  found:    java.util.HashSet
09:19:12,368 [WARNING] /home/jonesn/src/egeria/open-metadata-test/open-metadata-fvt/view-services-fvt/glossary-author-fvt/src/main/java/org/odpi/openmetadata/viewservices/glossaryauthor/fvt/CategoryFVT.java:[273,34] unchecked conversion
  required: java.util.Set<java.lang.String>
  found:    java.util.HashSet
09:19:12,368 [WARNING] /home/jonesn/src/egeria/open-metadata-test/open-metadata-fvt/view-services-fvt/glossary-author-fvt/src/main/java/org/odpi/openmetadata/viewservices/glossaryauthor/fvt/client/glossarys/GlossaryAuthorViewGlossaryClient.java:[151,38] unchecked conversion
  required: java.util.Map<java.lang.String,java.lang.String>
  found:    java.util.HashMap
09:19:12,368 [WARNING] /home/jonesn/src/egeria/open-metadata-test/open-metadata-fvt/view-services-fvt/glossary-author-fvt/src/main/java/org/odpi/openmetadata/viewservices/glossaryauthor/fvt/CheckSerializationFVT.java:[195,30] unchecked cast
  required: ForCast
  found:    L
:
```
I also hit #6143 - but that affects all FVTs so leave that fix to there

On performance @davidradl -- the reason this test is a lot quicker, is that we are just running with the inmemory server (repo) (as well as the view server). For the other FVTs we run against BOTH inmemory AND JanusGraph. It is this parameterized test that is causing the slow performance in #5938 .

The plan is to move the JanusGraph connector out, and given that, plus wanting to avoid another big leap in test times, I would stick as-is, and DO NOT add the JanusGraph test UNLESS you remove all the subject area FVT. If you do, it's probably wise to include graph as otherwise we won't have any testing of that area in the graph, at least in automation.

**Review by planetf1 — CHANGES_REQUESTED** [review]
Changes look good - if the compile wanrnings from javac & codeQL are fixed up.

**Comment by davidradl** [comment]
> > @odttlnt There are some code scanning errors - that are failing the build - should be easy fixes I think/
> 
> So there are in all 5 errors. The fifth error is for a unused variable. I will correct that. The remaining ones are for some variation of code like termForUniqueQFN2 == null || termForUniqueQFN2.equals("")). Now this same code is there in the SubjectArea FVTs. Wondering if there was some setting in CodeQL that passed that code but is erroring out for this one.

I am not sure of a setting.

**Comment by davidradl** [comment]
Hi , the inequality tests are correctly raising errors I think that a String should not be compared to a Glossary. I suspect these errors were incorrectly ignored for the subject area . Please could you fix the subject area and the glossary author test code to correct the compares.

**Pull request closed without merging**
