### PR TITLE
Software Server Capabilities - add endpoint for creation of the entity and for fetching it

### PR DESCRIPTION
**Pull request by danielaotelea**

### CODE REVIEW

**Comment by schannamallu** [comment]
recheck

**Comment by planetf1** [comment]
@danielaotelea  I'll take a look at the javadoc error this pm. I made a change yesterday which did go in clean, but this build appears to be reporting an error in the top level pom :-(

**Comment by planetf1** [comment]
I can see later PRs have gone through ok. I suggest rebasing/merging with current upstream master, then hopefully it will build clean.

**Comment by planetf1** [comment]
recheck

**Pull request merged**
