### PR TITLE
Release 1.2 - additional CTS backports including 2091

### PR DESCRIPTION
**Pull request by planetf1**
#2091 backport for release 1.2

### CODE REVIEW

**Comment by cmgrote** [comment]
Ack!  Sorry, just noticed that I didn't rename the variable in the k8s job yamls -- let me put in a new PR against master for that fix...

**Comment by planetf1** [comment]
Fine - but we need the commit ids on odpi/egeria before I can cherry-pick effectively - so will do once #2106  is merged....

**Comment by planetf1** [comment]
So are #2098 and #2102 fixes needed here too @grahamwallis @cmgrote

**Comment by cmgrote** [comment]
> So are #2098 and #2102 fixes needed here too @grahamwallis @cmgrote

Yes for #2102 for me, up to @grahamwallis for #2098

**Comment by planetf1** [comment]
Now getting merge conflicts on further changes. I will need to try applying in a different order so closing.

**Pull request closed without merging**
