### PR TITLE
Apache Atlas docker and k8s changes

### PR DESCRIPTION
**Pull request by cmgrote**
- Configures vanilla Apache Atlas container to tail all log files by default (not only `application.log`)
- Adds container-external accessibility to embedded Apache Atlas Kafka event bus
- Adds parameters for Apache Atlas container (eg. credentials, endpoints, etc)
- Swaps forked Apache Atlas container as default to the vanilla Apache Atlas container
- Configures Apache Atlas proxy as part of `egeria` container itself, rather than a separate container

### CODE REVIEW

**Comment by planetf1** [comment]
From a development perspective it's a good change... I'll float the suggestion with a few people I currently have pulling the charts to check for impact before merging

**Comment by planetf1** [comment]
I've confirmed at least one user is making use of atlas ui for browsing. Likely terms/glossaries. I noted current UI is failing also so opened up https://github.com/odpi/egeria/issues/1129

I suggest we need to hold off merging just yet.

**Comment by cmgrote** [comment]
Sure thing -- let's leave open for now.  I was under the impression that the forked Atlas build may be broken already, in which case this was at least something.  But if not, let's leave as-is for now 👍

**Comment by planetf1** [comment]
Ok. I will double check if it works now (it was ok), but have a  few people confirm they are using it. Obviously if we make it optional then we can merge now. I think the availability of Egeria UIs will allow us to make the change finally as I completely agree in not wanting to prolong the use of forked atlas much longer.

**Comment by schannamallu** [comment]
recheck

**Comment by planetf1** [comment]
Can confirm 'old' atlas is working propertly, so continuing to wait until new UI is available in lieu of atlas UI for simple search

**Pull request merged**
