### PR TITLE
Ensure federated query (#6311)

### PR DESCRIPTION
**Pull request by mandy-chessell**
Signed-off-by: Mandy Chessell <mandy.e.chessell@gmail.com>

# Description

1. Change the find executors so they always return false - this causes them to traverse all repositories
2. Update integration connectors to supply a component description for the audit log
3. Change the admin services ServerStatus to ServerServicesStatus to avoid name clash with platform services ServerStatus
4. Update the methods in the SoftwareServerPlatform beans from setSoftwareServerXXX to setSoftwareServerPlatformXXX

Fixes # (issue)

# How Has This Been Tested?

FVT - hoping that @alexandra-bucur will test with config that does not emit events from one of the repositories.

# Any additional notes for reviewers?

### CODE REVIEW

**Comment by planetf1** [comment]
@mandy-chessell The underlying issue has been fixed & tested in master now, so you should be able to merge with master & the checks should work ok. (see https://github.com/odpi/egeria/issues/6326 )

**Comment by alexandra-bucur** [comment]
@mandy-chessell I will test it as soon as it gets in master. I cannot pull code from your fork.

**Comment by alexandra-bucur** [comment]
I tested the search and it works fine, but the publishing of the glossary term through Asset Lineage is not working.  It relies on the GetRelationshipsForEntityExecutor which was not changed. Along with it I saw that there are another 11 executors without this new logic, but I am not aware of the impact of their behaviour.

**Comment by mandy-chessell** [comment]
I have updated getRelationshipsForEntity and getAllTypeDefs

**Comment by alexandra-bucur** [comment]
It works fine now. Thank you!

**Pull request merged**
