### PR TITLE
Fix assemblies and remove Connected Asset OMAS

### PR DESCRIPTION
**Pull request by mandy-chessell**

### CODE REVIEW

**Comment by mandy-chessell** [comment]
recheck

**Comment by mandy-chessell** [comment]
recheck

**Comment by planetf1** [comment]
This probably fixes the root cause behind https://github.com/odpi/egeria/issues/1006

**Comment by planetf1** [comment]
This verification failure may be caused by https://github.com/odpi/ci-management/issues/62#issuecomment-492415461

**Comment by mandy-chessell** [comment]
recheck

**Comment by planetf1** [comment]
recheck

**Pull request merged**
