### PR TITLE
Integration Daemons and Engine Hosts

### PR DESCRIPTION
**Pull request by mandy-chessell**
This PR contains fixes to the integration daemon for the DB connectors.

It also includes:
* New interfaces for the Governance Engines (See GAF modules).
* New engine-host-services that supports common event and configuration management for all engine services
* Bug fixes to the Discovery Engine OMAS around Governance Engine Definitions
* Updates to Asset Analysis OMES to support new engine services
* Updates to admin guide for new engine-host-services
* Addition of @Override tags to various connector classes and access services clients

### CODE REVIEW

**Comment by mandy-chessell** [comment]
I can not get the gradle build to work - it is failing with the message `Deprecated Gradle features were used in this build, making it incompatible with Gradle 6`. I can not see anything obviously wrong.

In the process of trying to fix it I added missing clients and connectors and combined the in-memory and the readonly repository connectors into one jar (since the read only a the production repository connector and depends on the in-memory).  None of these solved the problem but have made the gradle build more consistent with the mvn build.

**Comment by planetf1** [comment]
The gradle errors can be determined with `./gradlew build --warning-mode=all` . The errors I see for deprecation are:

```
> Configure project :open-metadata-test:open-metadata-fvt:access-services-fvt:asset-manager-fvt
The testCompile configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 7.0. Please use the testImplementation configuration instead. Consult the upgrading guide for further information: https://docs.gradle.org/6.7/userguide/upgrading_version_5.html#dependencies_should_no_longer_be_declared_using_the_compile_and_runtime_configurations
        at build_2q6l7m0dw4pphg29e4ac4pebn$_run_closure1.doCall(/Users/jonesn/IdeaProjects/egeria.maven/open-metadata-test/open-metadata-fvt/access-services-fvt/asset-manager-fvt/build.gradle:20)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
        ```
So change
```
     testCompile("org.junit.jupiter:junit-jupiter-params")
     ```
to
```
     testImplementation("org.junit.jupiter:junit-jupiter-params")
     ```        
     See https://docs.gradle.org/current/userguide/java_library_plugin.html
     
     It may also be relevant to use 'testCompileOnly' depending on what is needed from the dependency - the doc above gives full details. (we mostly use testImplementation)

**Comment by mandy-chessell** [comment]
Thank you @planetf1  - The Asset Manager FVT needs exactly the same options as the other Access Service FVTs.   I noticed that the new data engine fvt also uses testCompile - I have updated that one too ...

**Comment by planetf1** [comment]
@mandy-chessell Are you happy with the assemblies that are built after these changes? These can be found at egeria/open-metadata-distribution/open-metadata-assemblies/target/egeria-2.6-SNAPSHOT-distribution/egeria-omag-2.6-SNAPSHOT after a maven build, & for gradle in open-metadata-distribution/open-metadata-assemblies/build/distributions/egeria-2.6-SNAPSHOT-distribution.tar.gz

From a cursory look I wonder if some of the changes you'd planned are not reflected here, which may cause issues when we use dynamic loading. I would expect some more of the connectors to feature 

Having checked a prior build I don't see any regression here, but reviewing your PR made me wonder if you expect more to be in the assemblies?

Note - the maven build publishes assemblies which can be checked on a PR ie https://github.com/odpi/egeria/actions/runs/460959487 (see bottom)
The gradle build doesn't (yet)

For ref, the current connectors in the assembly with master are:
```
audit-log-console-connector-2.6-SNAPSHOT.jar                  discovery-service-connectors-2.6-SNAPSHOT.jar
audit-log-event-topic-connector-2.6-SNAPSHOT.jar              discovery-service-sample-2.6-SNAPSHOT.jar
audit-log-file-connector-2.6-SNAPSHOT.jar                     files-integration-connectors-2.6-SNAPSHOT.jar
audit-log-slf4j-connector-2.6-SNAPSHOT.jar                    graph-repository-connector-2.6-SNAPSHOT.jar
avro-file-connector-2.6-SNAPSHOT.jar                          inmemory-open-metadata-topic-connector-2.6-SNAPSHOT.jar
basic-file-connector-2.6-SNAPSHOT.jar                         inmemory-repository-connector-2.6-SNAPSHOT.jar
cassandra-data-store-connector-2.6-SNAPSHOT.jar               kafka-open-metadata-topic-connector-2.6-SNAPSHOT.jar
cassandra-metadata-extractor-connector-2.6-SNAPSHOT.jar       omrs-rest-repository-connector-2.6-SNAPSHOT.jar
cohort-registry-file-store-connector-2.6-SNAPSHOT.jar         open-lineage-janus-connector-2.6-SNAPSHOT.jar
configuration-encrypted-file-store-connector-2.6-SNAPSHOT.jar open-metadata-archive-file-connector-2.6-SNAPSHOT.jar
configuration-file-store-connector-2.6-SNAPSHOT.jar           open-metadata-security-samples-2.6-SNAPSHOT.jar
csv-file-connector-2.6-SNAPSHOT.jar                           readonly-repository-connector-2.6-SNAPSHOT.jar
data-folder-connector-2.6-SNAPSHOT.jar                        spring-rest-client-connector-2.6-SNAPSHOT.jar
```

**Comment by mandy-chessell** [comment]
There seem to be 2 problems -
* `readonly-repository-connector-2.6-SNAPSHOT.jar` should not exist
* `governance-action-connectors-2.6-SNAPSHOT.jar` should be included

The rest look ok

**Comment by planetf1** [comment]
I must have made a mistake checking the assembly. Checked the last merge build https://github.com/odpi/egeria/actions/runs/463881074 and the built assembly is exactly as you list above - and as coded in the maven assembly. So we're good there.

I've not run the gradle build (it's still work in progress) but the definitions look to be updated correctly.

So I don't think any action is needed here. false alarm.

**Pull request merged**
