### PR TITLE
odpi/egeria#3726 - Option to allow saveInstanceReferenceCopies() to be called in real metadata collection [master]

### PR DESCRIPTION
**Pull request by jnhagelberg**
See https://github.com/odpi/egeria/issues/3726

We would also like to get this into egeria 2.3, if that is still possible.  The PR for that is #3728.

### CODE REVIEW

**Comment by jnhagelberg** [comment]
@wbittles I have pushed changes to address your review comments

**Comment by planetf1** [comment]
Note there are some really useful comments and discussion in the 2.3 PR, but as 2.3 is shipping we need to focus on the fix for master/2.4 - which is this PR.

see https://github.com/odpi/egeria/pull/3728

**Comment by jnhagelberg** [comment]
@wbittles @mandy-chessell Do have any further comments about this?

**Comment by jnhagelberg** [comment]
@planetf1 Any comments?

**Review by mandy-chessell — CHANGES_REQUESTED** [review]
The changes that are proposed are not what I would have expected - in fact more complex than I think is needed.  The `isAutomicallySplitBatchMessages()` method is not necessary.  All that is needed  is to implement the method in LocalOMRSMetadataCollection to pass the call through to the real metadata collection.  If the real metadata collection has not implemented the method, the default implementation in `OMRSMetadataCollection` is used which splits up the messages.  If the real metadata collection wants to override the default implementation then they can.

The administration changes are also not needed.

Finally, please format any code changes in a layout that is consistent with the rest of the module - as per our coding guidelines.

**Comment by jnhagelberg** [comment]
@mandy-chessell The problem with that is that if we always forward the call to the real metadata collection we are breaking backward compatibility.  For example, our implementation does override `saveInstanceReferenceCopies()`, but the method is never being called.  Granted, we did add that method with the expectation that it would be called, but at this point because egeria is not calling it our implementation is largely untested.  However, we do have tests would catch any problems.

Having said that, it is definitely simpler to not have the toggle and associated configuration.  If you are not concerned about the backward compatibility, I can change the implementation to remove the toggle.  If we do that, though, it definitely needs to be documented as a behavior change in the release notes.

**Comment by jnhagelberg** [comment]
@mandy-chessell Based in your comments I have removed the toggle.  If you decide it is still needed I can remove that commit from the PR.

**Comment by mandy-chessell** [comment]
With the simple fix, the backward compatibility for the repository connector that has not overridden the method because it pre-dates the new method is fine.

The simple fix is only a problem for a repository connector that has overridden the method with an invalid (buggy) implementation.  I am not too worried about the second case as this is a repository connector that is aware of the method and has attempted to implement it.  Presumably they have tested it too and are just annoyed/puzzled why it is not being called.

**Comment by jnhagelberg** [comment]
@mandy-chessell Sounds good.  In that case, can you please review the changes again and let me know if you have any further comments?

**Review by mandy-chessell — APPROVED** [review]

**Comment by jnhagelberg** [comment]
@planetf1 Mandy approved the code review.  Can you please merge the changes if there are no further comments?

**Comment by jnhagelberg** [comment]
@mandy-chessell @wbittles ^^

**Pull request merged**
