### PR TITLE
Implement nginx proxy for lab helm chart

### PR DESCRIPTION
**Pull request by planetf1**
- Adds new nginx container
- configures nginx using template
- directs front end requests at static UI, backend at ui server chassis
- utilizes secrets for tls cert/key and configmap for nginx template
- environment provided by k8s deployment
- certs currently copied in-situ into a secret yaml file (not a secure approach - initial step)

Currently testing

### CODE REVIEW

**Comment by planetf1** [comment]
Debugging the specific cert chosen for now:
```
2021/03/19 08:51:44 [emerg] 1#1: cannot load certificate "/etc/nginx/ssl/tls.crt": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)
nginx: [emerg] cannot load certificate "/etc/nginx/ssl/tls.crt": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)

```
The primary purpose of this initial change is to get something working to allow for zuul removal.
A later PR may be used to ensure a user specified secret may be used instead

**Comment by planetf1** [comment]
@lpalashevski How familar are you with nginx's certificate needs? Currently I am basing the encoded certificate on those we generate under open-metadata-resources/open-metadata-deployment/certificates as a proof point, Just trying to debug the specific nature of the problem with the certs (where every tool seems different)

**Comment by planetf1** [comment]
To view the certs one can use 
```
kubectl get secret lab-nginx-ssl -o json | jq '.data | map_values(@base64d)'
```

**Comment by planetf1** [comment]
The error was caused by 2 problems in the helm template for nginx
 a) I had only a tls.cert, with the contents of tls.key (mapping error)
 b) I did not specify the private key password, and have added a new volume for this
 
 Not secure, but proving the concepts.

**Comment by planetf1** [comment]
Current status - the existing UI does not work. Nginx is now being configured correctly and returns the same result.
cc: @bogdan-sava @lpalashevski @sarbull

**Comment by planetf1** [comment]
See also https://github.com/odpi/egeria-ui/pull/111
If we make a change that involves the static UI switching to a different port (as it does in that PR) then I will need to adjust the ports here accordingly

Note also that once merged I still need to fix up docker compose before we can remove zuul

Finally note that in any case the polymer UI is currenly not working as per https://github.com/odpi/egeria-ui/issues/110

**Comment by planetf1** [comment]
This is ready to be merged.
As per #4549 still need to update compose & make some doc updates in readmes, notebook.

**Review by lpalashevski — APPROVED** [review]

**Pull request merged**
