### PR TITLE
Adds a maxSearchResults parameter for CTS repository workbench

### PR DESCRIPTION
**Pull request by cmgrote**
Also changes REST endpoint for configuring the workbench to POST with body (rather than purely URL-path-based).

### CODE REVIEW

**Comment by cmgrote** [comment]
Testing on my side before readying for merge:

- [ ] that configuration of this new page size parameter is stored in and visible from the config document for the server
- [ ] that sending in a page size (eg. of 5) is properly passed through and used in the tests
- [ ] that not sending in any page size uses the fall-back default (a page size of 50)

**Comment by mandy-chessell** [comment]
Could we use a different term than pageSize so that there is no confusion

**Comment by cmgrote** [comment]
@planetf1 @grahamwallis can either of you create a backport of this for release-1.2 as well, please?  Not sure how to do it myself, so don't want to destroy anything in my first attempt at doing so 😬

**Comment by planetf1** [comment]
> @planetf1 @grahamwallis can either of you create a backport of this for release-1.2 as well, please? Not sure how to do it myself, so don't want to destroy anything in my first attempt at doing so 😬

I can -- once it's merged into master. Looks fine to me, though I note a discussion about page size. I'm ok with page size - we do have them elsewhere, but it's a general concept?

**Comment by cmgrote** [comment]
> I can -- once it's merged into master. Looks fine to me, though I note a discussion about page size. I'm ok with page size - we do have them elsewhere, but it's a general concept?

Thanks!  pageSize comment was resolved offline (on Slack) -- so merging now, if you can go ahead and backport it as well 🙏 🙇

**Comment by planetf1** [comment]
I think https://github.com/odpi/egeria/pull/2103 captures it? Can you take a look? will likely check in morning.

**Pull request merged**
