### PR TITLE
Changes to the way unsupported functions are reported

### PR DESCRIPTION
**Pull request by grahamwallis**
Signed-off-by: Graham Wallis <graham_wallis@uk.ibm.com>

### CODE REVIEW

**Comment by cmgrote** [comment]
Testing locally and will update as soon as I have results (probably ~1 hour)...

**Comment by cmgrote** [comment]
Yes, this looks good -- now seeing that current property searches are `CONFORMANT_FULL_SUPPORT` and metadata maintenance profile (where entity lifecycle resides) is `CONFORMANT_NO_SUPPORT`

**Comment by planetf1** [comment]
Is this also expected for 1.2?

**Comment by cmgrote** [comment]
I would suggest yes, as without these changes read-only repositories can never by conformant with the mandatory profile...

**Comment by grahamwallis** [comment]
Yes definitely want this in 1.2

**Pull request merged**
