### PR TITLE
ergeria#1778 - Merge changes into 1.1 release

### PR DESCRIPTION
**Pull request by jnhagelberg**
@mandy-chessell @planetf1 We would like to get these changes into 1.1 if possible.  I did not realize there was a separate branch for that.  WKC will be picking up the 1.1 release, we probably won't be able to pick up 1.2 for some time.  I noticed my other fix did not make it into the 1.1 branch.  That is included here as well.

### CODE REVIEW

**Comment by jnhagelberg** [comment]
PR build failed with "Caused by: org.apache.maven.plugin.MojoFailureException: Could not download Node.js: Got error code 500 from the server".  Retrying build.

**Comment by jnhagelberg** [comment]
Closing, as discussed in Slack it seems that we can wait for 1.2

**Comment by mandy-chessell** [comment]
recheck

**Comment by jnhagelberg** [comment]
Reopening, since it seems that we might still need to get the changes into 1.1

**Comment by planetf1** [comment]
Testing the PR/any regression (should be fine as in master) then will merge

**Pull request merged**
