### PR TITLE
Close consumer gracefully #2991

### PR DESCRIPTION
**Pull request by wbittles**
This PR address both issues raised in #2991 and #3144

The First commit is the fix that means the TopicConnector now waits for both client threads to close, and removes an uncalled method "stop".
The second commit add exception handling to the calls to the consumer.commitSync().

### CODE REVIEW

**Comment by planetf1** [comment]
If we fail to update the sync point I am presuming that what will happen is that when next started (which is likely) we will end up potentially re-processing some messages. Most of the time we sync quickly in any case, and we should be able to handle a duplicate message, so I don't think this adds undue concern. If we are concerned we probably need to unwrap the next level of analysis and testing (beyond the high level architecture) in terms of everything around transactionality...

**Comment by grahamwallis** [comment]
@planetf1 - Agreed - the fact that this is consumer side, as you say, means we would duplicate not drop a message.

**Comment by planetf1** [comment]
I think we're good here then and should merge once the build is up to date...
(Note that it will be going into 2.1)

**Comment by wbittles** [comment]
@grahamwallis  and @planetf1 In this case I believe the root cause is that there isn't actually a message consumed, we've opened a transacted poll, no message has arrived and then we issued a WakeUP and tried to commit an empty transaction. I don't think there is any underlying problem , (except that the consumer doesn't track if there is anything to actually commit , before calling commitSync )

**Pull request merged**
