### PR TITLE
Add mandatory javadoc & sources for maven central release (master) (NO MERGE YET)

### PR DESCRIPTION
**Pull request by planetf1**
This PR enforces the default javadoc build, excluding fvt (ie for opentypes)
It also adds empty jar files for sources & javadoc as this is mandatory for all artifacts for maven central

See #1110 for more info

NOTE: DO NOT MERGE until the javadoc errors are addressed.
cc: @mandy-chessell

### CODE REVIEW

**Comment by planetf1** [comment]
recheck

**Comment by askb** [comment]
recheck

**Comment by schannamallu** [comment]
recheck

**Comment by planetf1** [comment]
recheck

**Comment by schannamallu** [comment]
recheck

**Comment by askb** [comment]
recheck

**Comment by askb** [comment]
recheck

**Comment by planetf1** [comment]
recheck

**Comment by schannamallu** [comment]
recheck

**Comment by tykeal** [comment]
recheck

**Comment by tykeal** [comment]
recheck

**Comment by tykeal** [comment]
recheck

**Comment by tykeal** [comment]
recheck

**Comment by tykeal** [comment]
recheck

**Comment by askb** [comment]
recheck

**Comment by askb** [comment]
recheck

**Comment by askb** [comment]
recheck

**Comment by askb** [comment]
recheck

**Comment by planetf1** [comment]
recheck

**Comment by planetf1** [comment]
Given the large scale of pom changes recently I'll leave this PR open, but once javadoc works in the build or at least @mandy-chessell you have finished, I'll revisit and either fix up this PR or close and open new one to merge the javadoc checks into the build

**Comment by planetf1** [comment]
This PR is now quite out of date wrt base since we don't yet have all clean javadoc build
If necessary it can be closed and I will remerge into the larger pom changes at a later date
cc: @mandy-chessell @bogdan-sava

**Pull request closed without merging**
