### PR TITLE
#276 checkin initial helm charts for egeria deployment to kubernetes

### PR DESCRIPTION
**Pull request by planetf1**
Signed-off-by: Nigel Jones <nigel.l.jones+git@gmail.com>

### CODE REVIEW

**Comment by planetf1** [comment]
The paths that refer to planetf1 are not local files, they are pointers to a repository on docker.io, which is the default docker repository

Ideally I would like us to build docker images as part of egeria, or an associated project. Even better if we could do that under a 'odpi' id on docker hub, but that is going to take a while. We could also not publish the images anywhere except internally to the build environment/odpi infra, but that leaves a lot more work for anyone else to do.

The expedient approach was to post 'good enough' (and open) images to docker.io which anyone can use. This is what I've done so far for egeria, gaian, ranger. It will allow us to get started, learn by experience, invite broader collaboration, and quickly get to the point where we can deploy an egeria centric infrastructure with minimal effort - which is an acute challenge right now 

The references to myapp.name as to a variable. This is defined within each chart, and follows what appears to be a 'best practice'. Each kubernetes 'artifact' is tagged with the basename of the app uised to create it, and a component identifier. This makes it easier to search for, especially if the same k8s environment is hosting many many instances of egeria 

Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

The value of myapp is determined in _helpers.tpl . The default will be generated automatically by k8s. this is where we get the 'odd' names for a deployment as seen in the README.md. That is 'normal' behaviour. I think that makes it good for now - without duplicates (though am still working on testing).

Note I've not completed the ranger/vdc setups yet.

**Comment by planetf1** [comment]
@bogdan-sava hi can you take a look and see if the response answers your questions? Thanks for reviewing

**Comment by planetf1** [comment]
An addition on the choice of repository.

From https://kubernetes.io/docs/concepts/containers/images/
There are a number of solutions for configuring private registries. Here are some common use cases and suggested solutions.

Cluster running only non-proprietary (e.g. open-source) images. No need to hide images.
Use public images on the Docker hub.
No configuration required.

For getting started this made it the obvious choice. The same doc covers use of other container repos.

**Comment by planetf1** [comment]
Here's the links to the 'experimental' images thus far
https://hub.docker.com/u/planetf1/

**Comment by planetf1** [comment]
@bogdan-sava Hi - could you check if my comments satisfied your concerns?

**Comment by bogdan-sava** [comment]
Yes. Fair enough. It would be great if you can show a demo of how to use.

**Pull request merged**
