### PR TITLE
Fixes issues with appropriate attribute types

### PR DESCRIPTION
**Pull request by cmgrote**
Refactors the mapping logic for the IGC connector so that it properly adheres to the `TypeDefAttribute` definitions when setting primitive property values -- should correct the issue seen previously where the connector was generating events with strings instead of integers, for example.

(Also inadvertently pointed out that a fix was needed on a couple mappings for entities where I'd mixed up `displayName` and `name`.)  And Sonar pointed out that my status checking on the various search operations probably wasn't doing what I expected, so might have fixed a bug there, too.

@mandy-chessell I added some additional helper methods to the `OMRSRepository[Content]Helper` to fill in the gaps on primitive property types that weren't already covered by the other helpers (but that do show up in the open metadata archive) -- followed same conventions as others, but please have a double-check.

### CODE REVIEW

**Comment by ruxandraRosu** [comment]
Hi @cmgrote I've done a new test for semantic assignment and I am seeing exceptions: 
019-01-25 13:29:19.559 ERROR 11926 --- [https-jsse-nio-8443-exec-3] o.a.c.c.C.[Tomcat].[localhost]           : Exception Processing ErrorPage[errorCode=0, location=/error]

org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.springframework.http.MediaType.isPresentIn(Ljava/util/Collection;)Z
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1053) ~[spring-webmvc-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) ~[spring-webmvc-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) ~[spring-webmvc-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897) ~[spring-webmvc-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[tomcat-embed-core-9.0.14.jar!/:9.0.14]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882) ~[spring-webmvc-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.14.jar!/:9.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.14.jar!/:9.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.14.jar!/:9.0.14]
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) ~[tomcat-embed-core-9.0.14.jar!/:9.0.14]
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:461) ~[tomcat-embed-core-9.0.14.jar!/:9.0.14]
        at org.apache.catalina.core.Application

**Comment by ruxandraRosu** [comment]
Also I can see this exception in atlas log so I think there is an error for one of the relationships org.apache.atlas.exception.AtlasBaseException: invalid relationshipDef: AssetSchemaType: end type 1: SchemaType, end type 2: DataFile
        at org.apache.atlas.repository.store.graph.v2.AtlasRelationshipStoreV2.validateRelationship(AtlasRelationshipStoreV2.java:626)
        at org.apache.atlas.repository.store.graph.v2.AtlasRelationshipStoreV2.create(AtlasRelationshipStoreV2.java:129)
        at org.apache.atlas.repository.store.graph.v2.AtlasRelationshipStoreV2$$FastClassBySpringCGLIB$$a8165974.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.apache.atlas.GraphTransactionInterceptor.invoke(GraphTransactionInterceptor.java:77)

**Comment by mandy-chessell** [comment]
Should we be merging this - not sure if this is a new issue or the same problem?

**Comment by ruxandraRosu** [comment]
I can see in endpoint entity that networkAddress is empty, was this change reverted? This was fixed in a previous build.

**Comment by cmgrote** [comment]
> I can see in endpoint entity that networkAddress is empty, was this change reverted? This was fixed in a previous build.

Yes, my mistake -- my update changed that, but now it should be back to working again from my last commit.

**Comment by cmgrote** [comment]
> Also I can see this exception in atlas log so I think there is an error for one of the relationships org.apache.atlas.exception.AtlasBaseException: invalid relationshipDef: AssetSchemaType: end type 1: SchemaType, end type 2: DataFile

The code on the IGC side for this hasn't changed; I suspect it's the improved error detection on Atlas's side.  This reminds me that I'm trying to treat a `DataFile` entity as an Asset in this relationship (and `DataFile` only extends `Referenceable` and not `Asset`).  @mandy-chessell assuming that `DataFile` is intentionally *not* an `Asset`, do we have any equivalent to represent a file as an asset for such schema relationships?

**Comment by cmgrote** [comment]
> Hi @cmgrote I've done a new test for semantic assignment and I am seeing exceptions. The exception is caused by getTypeDefByName request used by iv omas. Would you please have a look?

I'm not recognising anything in the stack trace you pasted... It seems to indicate that Spring itself isn't finding a method that it expects (a method called `org.springframework.http.MediaType.isPresentIn(Ljava/util/Collection;)` ?)  Could this have been caused by @bogdan-sava 's update to SpringBoot 2.1.2 from 2.1.1?  There isn't anywhere I'm explicitly trying to use that method...  (I'm assuming you've done a full "mvn clean install" after updating with this PR to ensure all libraries, etc are updated?)

stackoverflow threads with similar errors seem to suggest it's a potential dependency problem where some other dependency (which itself depends on Spring) is loading a different version of the Spring libraries before Spring itself is loaded (?)  (https://stackoverflow.com/questions/38442676/java-lang-nosuchmethoderror-org-springframework-http-mediatype-getcharsetljav)

**Comment by ruxandraRosu** [comment]
Hi, I ran mvn clean install. It might not be updated to latest master, I will pull the changes and retest. I' ll update the PR with the status.

**Comment by mandy-chessell** [comment]
@cgrote DataFile should inherit from DataStore which makes it an Asset. The documentation is correct. See https://odpi.github.io/egeria/open-metadata-publication/website/open-metadata-types/0220-Files-and-Folders.html.  The implementation is wrong.  I'll fix.

**Comment by cmgrote** [comment]
> @cgrote DataFile should inherit from DataStore which makes it an Asset. The documentation is correct... The implementation is wrong. I'll fix.

😌 phew!  thought I'd need to rethink how to represent data files 👍

**Comment by ruxandraRosu** [comment]
Endpoint issue is fixed

**Comment by ruxandraRosu** [comment]
Raised issues https://github.com/odpi/egeria/issues/650 and https://github.com/odpi/egeria/issues/651

**Pull request merged**
