### PR TITLE
#2942 create patch for ProjectScope

### PR DESCRIPTION
**Pull request by davidradl**
Signed-off-by: David Radley <david_radley@uk.ibm.com>

### CODE REVIEW

**Comment by davidradl** [comment]
@mandy-chessell ok I see. I am happy for you to take this and include it as part of the wider change. I am glad I understand it better now

**Comment by mandy-chessell** [comment]
Merged create of OpenMetadataTypesArchive for 1.8

**Comment by mandy-chessell** [comment]
I am happy to make the change - or leave it open for you to do - should be straight forward now :)  Let me know

**Comment by davidradl** [comment]
closing to make the merge easier

**Pull request closed without merging**
