### PR TITLE
Spring dependencies update

### PR DESCRIPTION
**Pull request by planetf1**
This PR is open for review/comment/debug. See #1737 for background

Note that this is not complete yet (hence a draft). 

The Egeria Server chassis starts ok, but the UI fails with:
```
2019-10-17 13:10:05.274  WARN 61231 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'welcomePageHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.autoconfigure.web.servlet.WelcomePageHandlerMapping]: Factory method 'welcomePageHandlerMapping' threw exception; nested exception is java.lang.NoSuchMethodError: org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.getInterceptors()[Ljava/lang/Object; (loaded from jar:file:/Users/jonesn/IdeaProjects/egeria/open-metadata-implementation/user-interfaces/access-services-user-interface/target/access-services-user-interface-1.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-boot-autoconfigure-2.1.9.RELEASE.jar!/ by org.springframework.boot.loader.LaunchedURLClassLoader@80b66e6) called from class org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration (loaded from jar:file:/Users/jonesn/IdeaProjects/egeria/open-metadata-implementation/user-interfaces/access-services-user-interface/target/access-services-user-interface-1.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-boot-autoconfigure-2.1.9.RELEASE.jar!/ by org.springframework.boot.loader.LaunchedURLClassLoader@80b66e6).
```
```
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration.welcomePageHandlerMapping(WebMvcAutoConfiguration.java:453)

The following method did not exist:

    org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.getInterceptors()[Ljava/lang/Object;

The method's class, org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration, is available from the following locations:

    jar:file:/Users/jonesn/IdeaProjects/egeria/open-metadata-implementation/user-interfaces/access-services-user-interface/target/access-services-user-interface-1.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-boot-autoconfigure-2.1.9.RELEASE.jar!/org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class

It was loaded from the following location:

    jar:file:/Users/jonesn/IdeaProjects/egeria/open-metadata-implementation/user-interfaces/access-services-user-interface/target/access-services-user-interface-1.1-SNAPSHOT.jar!/BOOT-INF/lib/spring-boot-autoconfigure-2.1.9.RELEASE.jar!/


Action:

Correct the classpath of your application so that it contains a single, compatible version of org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration
```

### CODE REVIEW

**Comment by planetf1** [comment]
Thanks. Very interesting david as I've just made that change in the last 20 mins (testing) as I'd come to the same conclusion!

**Comment by planetf1** [comment]
My plan is to run through our 3 node 'lab' cohort scenario and check the notebooks function correctly, along with the UI, to provide for a base level of testing.

**Comment by planetf1** [comment]
Summary so far

* removing dependency exclusions for jackson annotations from OCF
* removing spring exclusions from UI
* satisfying UIs requirement for jakarta.persistence 2.2.3 (over javax.persistence) after dependency updates
* Adding jaxb-api 2.3.0 at runtime for hibernate (and an exclusion as not needed at compile time)
* slf4j 1.7.26 -> 1.7.28
* jackson 2.9.9/2.9.9.3 to 2.10.0
* springboot 2.1.6 to 2.2.0
* springdata 2.1.9 to 2.2.0
* spring 5.1.8 to 5.2.0
* spring security 5.1.5 to 5.2.0
* spring ldap - previously not locked. Now 2.3.2
* spring plugin - previously not locked. Now 2.0.0
* tomcat 9.0.27
* maven enforcer plugin 3.0.0-M1 -> 3.0.0-M2 (originally to check for correct reporting of dependency issues)
* cleaned up duplicate dependencyManagement entries
* added spring-aop, spring-jdbc, spring-ldap-core, spring-plugin-core, spring-plugin-metadata, spring-aspects to dependencyManagement as multiple versions were being resolved

However the current issue is that spring fox (which we use for documentation) is incompatible with the declared version of spring-plugin

**Comment by planetf1** [comment]
There is a lot of interdependency in spring & it's associated components. Full consistency is a challenge, and where other users (like swagger) don't keep up it can hold the whole stack back. A working combination can sometimes be found, but with such a variety of components it may mean mismatched or duplicate versions - and may differ each time updates are made. The thought process here was to consolidate only on the major spring web/boot/security/ etc groupIds ....

**Comment by bogdan-sava** [comment]
interdependencies are fixed and also tested with the changes of #1794

**Comment by bogdan-sava** [comment]
spring-boot 2.2.0 will **NOT** work with webmvc 5.2.0

**Comment by planetf1** [comment]
Closing (with no changes). Too many interdependent updates on this branch/PR.

**Comment by eric-delguerra** [comment]
Hi ! We got the same issue in my class and we see that this dependency : 
```
<dependency>  
	<groupId>org.springframework.boot</groupId>  
	<artifactId>spring-boot-starter-data-rest</artifactId>  
</dependency>
```
We removed this one and now it work.. And don't know if it's a solution but we can work now !

**Comment by planetf1** [comment]
Thanks @eric-delguerra . We are continuing the work in #1795 which is getting a lot closer. We're trying to keep as few versions as possible - so for example now just for spring, & springboot.

Will bear the comment in mind though and thanks for the suggestion! Will be glad when spring is sorted (for this round of updates!)

**Pull request closed without merging**
