### PR TITLE
#492 update atlas docker build with latest patches

### PR DESCRIPTION
**Pull request by planetf1**
Signed-off-by: Nigel Jones <nigel.l.jones+git@gmail.com>

See text in #492 - now updated with patches, mvn build install is clean (so can be merged) but docker build failing on spring issue currently.

### CODE REVIEW

**Comment by bogdan-sava** [comment]
I had no issues with previous patches.
I'll check thee current ones too.

**Comment by bogdan-sava** [comment]
Latest Atlas code build works.
After apply all 4 patches from https://issues.apache.org/jira/browse/ATLAS-1773
i get this error:
[ERROR] Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.11.1:docs (default) on project atlas-webapp: Enunciate compile failed. -> [Help 1]

**Comment by planetf1** [comment]
@bogdan-sava I didn't get the enunciate error. However I did get issues with the later spring version.

I created an atlas patch which I've added into my docker build - so i now seem to be able to go from atlas master, via the patches, to a runnable atlas. Will try some more tests.

By building in docker (which I need for demo environments) we should get consistent behaviour.

However the build will be fragile (depends on patches), plus as you mentioned we may still have too many interdependencies

**Comment by bogdan-sava** [comment]
Yes! Indeed. 
What I found until now is that this new version brings to atlas spring-web and also spring-boot of Egeria and shouldn't. And that's because the **ibm-igc-repository-connector** is brought to atlas and shouldn't. 
And, why i**bm-igc-repository-connector** it depends on s**pring-boot-starter-web**, which get's dependency of **embbeded-tomcat**?

Solution:

First exclude  **ibm-igc-repository-connector** from atlas. In **open-metadata** module pom.xml :
There is in two dependencies!


 <dependency>
            <groupId>org.odpi.egeria</groupId>
            <artifactId>repository-services-implementation</artifactId>
            <version>${egeria.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>log4j-over-slf4j</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.odpi.egeria</groupId>
                    <artifactId>ibm-igc-repository-connector</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.odpi.egeria</groupId>
            <artifactId>admin-services-server</artifactId>
            <version>${egeria.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>ch.qos.logback</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>log4j-over-slf4j</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.odpi.egeria</groupId>
                    <artifactId>ibm-igc-repository-connector</artifactId>
                </exclusion>
            </exclusions>
        </dependency> 



Next step is to exclude **admin-services-server** and **epository-services-implementation** from atlas-webapp as there is already dependency of open-metadata module.

**Comment by bogdan-sava** [comment]
It might be runnable but contains ibm-igc-repository-connector and even an embedded tomcat.

**Comment by planetf1** [comment]
Thanks for the investigation.
I can use this PR to build/package an atlas that at least is buildable, hopefully functional, and best-so-far. This could be at least used for a demo. On the basis it's an improvement of what goes before & a tactical aid in enabling demos,  I'd like to integrate it into master so it's consistent with docker hub.

It also means in parallel i can continue to work on any automation of the docker build with the LF team.

I propose we open a new issue to track addressing the igc repo connector & tomcat dependencies, and it's super this issue was identified!.  I completely agree we should try and remove these dependencies from the atlas patch build, but this will take slightly longer

**Comment by planetf1** [comment]
Verified this PR results in a patched Atlas server that starts up when the 'vdc-open' helm chart is deployed
Merging this now so that I can now focus on inbound network routing to atlas (for external access to UI), linking to cohort, and configuring

**Pull request merged**
