### PR TITLE
Issue 5715 - add FVT for GlossaryAuthorView Rest services plus some f…

### LINKED ISSUE #5715: Add a new FVT for the Glossary Author OMVS
This would be very similar to the Subject Area FVT. There will need to be some scaffolding code when running this in the build so that the view servers are started prior to the test (see https://github.com/odpi/egeria/blob/master/open-metadata-test/open-metadata-fvt/access-services-fvt/subject-area-fvt/build.gradle for how this is done for the subject area omas FVT).

### PR DESCRIPTION
**Pull request by odttlnt**
…ixes done on pertinent services code.

- SubjectAreaDefinitionCategoryFVT, CheckSerializationFVT, EffectiveDatesFVT, RelationshipFVT, GraphFVT, ProjectFVT, TermFVT, CategoryFVT, GlossaryFVT
- Fix for glossaryAuthor NodeRelationshipStats Json deserialization and toString
- Glossary Author View Term Rest Service fix *** corrected code to return Term client
- Subject Area FVT fix to remove checked exception warning

Signed-off-by: Sachin Naik <odttlnt@gmail.com>

# Description
Glossary Author View FVTs created to validate functionality. Some other code outside of FVT also had to be changed

Fixes #5715

# How Has This Been Tested?

 mvn clean install  and gradle build, plus IDE build and run 
# Any additional notes for reviewers?
Warning message for CheckSerializationFVT is expected and is part of the FVT where it tries to check if the cast can be done.

### CODE REVIEW

**Review by davidradl — APPROVED** [review]

**Comment by davidradl** [comment]
@planetf1 are you ok for us to merge this?

**Comment by odttlnt** [comment]
@planetf1 let me know if you have any questions on the PR. This is for fixing Issue 5715

**Review by planetf1 — CHANGES_REQUESTED** [review]
Looks good overall. Needs updating from main (will always be the case after any merge) .I see there’s some codeQL reports - we’ve accumulated a lot in egeria overall so would be preferable if we can address them. 4 are warnings so should be dealt with - the others look minor, but also easier to address.

**Comment by odttlnt** [comment]
Git mess up . Closing pull request

**Pull request closed without merging**
