### PR TITLE
Fix open-metadata-conformance-suite

### PR DESCRIPTION
**Pull request by bogdan-sava**
Signed-off-by: Bogdan Sava <bogdan-mihail.sava@ing.com>

### CODE REVIEW

**Comment by bogdan-sava** [comment]
To run Open Metadata Conformance Test, after successful build, run in terminal:

`java -jar open-metadata-target/open-metadata-conformance-suite-1.1-SNAPSHOT.jar {server-name} {server-url}`

Ex:

`java -jar open-metadata-target/open-metadata-conformance-suite-1.1-SNAPSHOT.jar omas http://localhost:8080`

Result is:


```
===============================
Open Metadata Conformance Test  
===============================
Conformance Report for server: omas (http://localhost:8080)

Number of tests: 799
Number of tests passed: 799
Number of tests failed: 0
Number of tests skipped: 0

Congratulations, omas server at http://localhost:8080 is an open metadata repository
```

**Comment by mandy-chessell** [comment]
@bogdan-sava This fix does not seem to change the conformance suite itself.  Instead it is removing the use of GSON in other modules.  Is that right?  Does that mean we need to add a explicit requirement to the egeria method to ban the use of GSON?

**Comment by bogdan-sava** [comment]
Yes. It does two things: removes gson and replace the assembly plug-in with mavenj-jar-plug-in. After removing gson, worked from calling main method but still not from jar generated with assembly.
I know from experience that jar plug-in is more reliable, so I use it without more investigation.

I think mixing Jackson with gson is not good idea. However, if it is really needed, we can investigate about incompatibility and how to make them work.

**Comment by mandy-chessell** [comment]
Thanks for fixing this :)

**Pull request merged**
