### PR TITLE
Janus Connector - Adding transaction commits to lineage queries

### PR DESCRIPTION
**Pull request by lcpopa**
Signed-off-by: Liviu Popa <liviu-constantin.popa@ing.com>

### CODE REVIEW

**Review by lpalashevski — CHANGES_REQUESTED** [review]
Once e.printStackTrace() is removed its go to go

**Comment by grahamwallis** [comment]
During a recent demo of OLS we saw sleepycat timeouts which suggested that transactions were being left open, but it looks to me like this PR may well fix that.

**Comment by planetf1** [comment]
@lcpopa let me know when you are happy we can branch for 2.4 - presume that is once this is merged?

**Comment by lcpopa** [comment]
@grahamwallis According to https://docs.janusgraph.org/basics/transactions/ and https://groups.google.com/g/janusgraph-users/c/m-KMUc5zsHo we need to manually manage transactions when janusgraph is used as embedded, regardless if it is a read or write operation. Looks like reviewing some past code is in order and we already have planned that for the whole janus connector

@planetf1 I'll remove the code ljupcho mentioned and once merge, it's good to go

**Review by lpalashevski — APPROVED** [review]

**Comment by planetf1** [comment]
@lcpopa thanks. will merge once ready as it looks like the transaction issue @grahamwallis mentioned is out of scope for a pre-release fix and needs a longer review

**Pull request merged**
