### PR TITLE
#1039 Enables pre-commit build time significant improvement by skipping FVT 

### PR DESCRIPTION
**Pull request by planetf1**
…ild)

Added new option skipFVT (see #1039) to skip ALL fvt tests as part of precommit build

Signed-off-by: Nigel Jones <nigel.l.jones+git@gmail.com>

### CODE REVIEW

**Comment by askb** [comment]
recheck

**Comment by planetf1** [comment]
@davidradl @bogdan-sava @mandy-chessell are you ok with this change?

**Comment by bogdan-sava** [comment]
recheck

**Comment by planetf1** [comment]
builds currently down - reported at https://jira.linuxfoundation.org/servicedesk/customer/portal/2/IT-16387

**Pull request merged**
