### PR TITLE
#4082 Merged all UI files into new CRA-directories

### PR DESCRIPTION
**Pull request by jmmadsen**
This code will work locally. Authors need to confirm their pieces still work with Egeria. After this PR, need to fix Dockerfiles.

### CODE REVIEW

**Comment by planetf1** [comment]
set to draft so we can verify first (ie breakage of merge build)

**Comment by davidradl** [comment]
Hi @grahamwallis, please could you confirm that Tex Dino and Tex are as you expect. I will test Glossary Author

**Comment by grahamwallis** [comment]
Yes, will do - what is the new procedure for building with the revised folder structure?

I have been making further changes to Rex and Dino, so am hoping that the changes to the actual modules are minimal or zero, and that it's just the structure that has changed. @jmmadsen or @davidradl can you please confirm?

**Comment by jmmadsen** [comment]
@grahamwallis I have taken all the various changes from the `nodejs` directory, and applied them to the `cra-client` and `cra-server` directories - basically because the code in there was out of date.

**Comment by davidradl** [comment]
@jmmadsen I built the pr locally and ran a view server and metadata server. I had forgotten how to start the UI, I could not find how to do this in the docs in git. I had to look back in my slack messages and I ran npm start from the cra-server folder. If this is the way to start the dev ui please could you document this in the top level readme , which still refers to the old build system. Also mention how to build this in production mode. I suggest linking to the large cra readme md file from the top readme.

**Comment by davidradl** [comment]
Also the npm start failed with "Failed to compile.

./src/components/GlossaryAuthor/components/GlossaryAuthorNavigation.js
  Line 18:32:  Unexpected use of 'location'  no-restricted-globals
  Line 29:9:   Unexpected use of 'location'  no-restricted-globals

Search for the keywords to learn more about each error.
"

**Comment by davidradl** [comment]
the readme.md filein cra-client shows an error for me "Specification.COMMENT or Specification.SPEC_HEADING expected, got '## Table of Contents' "

**Comment by davidradl** [comment]
@jmmadsen I applied the pr and compared the glossary-author folder in nodejs and the one in cra-client, the one in nodejs has been back leveled. The file CategoryChildren is present in nodejs in master and in the the pr's cra-client . The pr's nodejs does not have CategoryChildren. It looks like the patch has backed off the latest changes from nodejs in glossaryauthor

**Comment by davidradl** [comment]
There are also differences between the repository explorer folders in nodejs and in cra-client. @grahamwallis is this what you would expect?

**Review by planetf1 — CHANGES_REQUESTED** [review]
Can you clarify how to build/run the client/server
I was hoping to look at what changes might be required for maven/gradle to get this packaged & run in our current container setup.

**Comment by jmmadsen** [comment]
@davidradl I will work on updating the ReadMe. I am not sure about the backleveling, perhaps just a manual error?

@planetf1 To run locally in production, run `npm build` from within `cra-client`, then run `npm prod` from within `cra-server`.

**Comment by planetf1** [comment]
> @davidradl I will work on updating the ReadMe. I am not sure about the backleveling, perhaps just a manual error?
> 
> @planetf1 To start in production mode locally, run `npm build` from within `cra-client`, then run `npm prod` from within `cra-server`.

```
jonesn:cra-client/ (jmmadsen-mergeCRA) $ npm build                                                                                                                                                           [15:47:40]
Top hits for "build"
————————————————————————————————————————————————————————————————————————————————
npm help install                                                         build:6
npm help config                                                          build:5
npm help explore                                                         build:5
npm help package-json                                                    build:4
npm help registry                                                        build:4
npm help rebuild                                                         build:4
npm help version                                                         build:4
npm help developers                                                      build:2
npm help semver                                                          build:2
npm help ci                                                              build:1
————————————————————————————————————————————————————————————————————————————————
(run with -l or --long to see more context)

```
I assume you mean:
```
jonesn:cra-client/ (jmmadsen-mergeCRA) $ npm run build                                                                                                                                                       [15:47:44]

> presentation-server-client@0.1.0 build
> react-scripts build

sh: react-scripts: command not found
npm ERR! code 127
npm ERR! path /Users/jonesn/IdeaProjects/egeria/open-metadata-implementation/user-interfaces/presentation-server/cra-client
npm ERR! command failed
npm ERR! command sh -c react-scripts build

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jonesn/.npm/_logs/2020-11-16T15_49_20_425Z-debug.log
```
But here we
 a) Need to get those tools into a form that can be retrieved as part of a build process (like maven-frontend-plugin)
 b) ensure we have a cross platform solution (windows needed too)

our build process does not assume the presence of locally installed tools

If this becomes essential I really think we need to split out the UI components into a seperate github project, as the requirements will become quite different to core egeria

**Comment by jmmadsen** [comment]
Hi @planetf1 you are correct I meant `npm run build` and `npm run prod` respectively.

I agree on your latter points. To get around the issues you are seeing locally, can you try running `npm install` in both `cra-client` and `cra-server` before the `npm` commands?

**Comment by planetf1** [comment]
@jmmadsen 

I ran `npm install` for my local environment which pulled in the dependencies, albeit taking over 4 minutes. The npm build then took another 3 minutes but failed with
```
jonesn:cra-client/ (jmmadsen-mergeCRA) $ npm run build                                                                                   [16:23:27]

> presentation-server-client@0.1.0 build
> react-scripts build

Creating an optimized production build...
Failed to compile.

./src/components/GlossaryAuthor/components/GlossaryAuthorNavigation.js
  Line 18:32:  Unexpected use of 'location'  no-restricted-globals
  Line 29:9:   Unexpected use of 'location'  no-restricted-globals

Search for the keywords to learn more about each error.

```

I am getting more convinced we need to move the UI code to a new repo - different language, skills, tools, process, pipelines, distribution - and my own feeling is +7 minutes for one components would be an undesirable to building the core.

**Comment by planetf1** [comment]
(that's just for the client)

**Comment by planetf1** [comment]
I have opened #4110 to split presentation server into it's own
I'm thinking a good seed for the code will be after this PR merge?
Does that make sense - then I will look through the build pipeline aspects?

**Comment by jmmadsen** [comment]
That makes sense to me. I will update once I'm able to take a look at it
again.

**Comment by grahamwallis** [comment]
@jmmadsen Hi Jacob - just a heads-up, I have opened PR #4114 to make a number of improvements to Rex. When you revisit this (4082) PR could you please pull across the latest Rex files from nodes/src/client/components/RepositoryExplorer?

**Comment by jmmadsen** [comment]
@grahamwallis Just pulled in your latest Rex code. Will update this PR with it soon.

**Pull request merged**
