### PR TITLE
OMAG servers startup list configuration #1512

### PR DESCRIPTION
**Pull request by bogdan-sava**

### CODE REVIEW

**Comment by mandy-chessell** [comment]
I think it is useful to have this approach for environments where a platform's servers are fixed.  I am not sure that the platform should keep running if it can not start one of the servers listed in the application properties particularly related to configuration documents or userId..

**Comment by mandy-chessell** [comment]
@bogdan-sava this is not quite the same issue.  If the server throws an exception from the instance startup message it is likely to be a permanent error - for example, the userId is not permitted to perform the action or there is a problem with the configuration document.

The failures once the server is running are more likely to be temporary and can be fixed by managing the resources.

In a production environment, the first type of error should never occur.  If the instance methods are called then the response says what is wrong.  When the servers are started from the property there is no way to return the response so the platform should fail.

**Comment by bogdan-sava** [comment]
platform shuts down means spring boot application shutdown or just deactivateTemporarily all the servers ?

**Comment by mandy-chessell** [comment]
Spring boot application should exit with a non-zero return code.  Ideally if it can deactivateTemporarily all of the running servers then that is a bonus.  No point in only shutting down the other servers as does not help the discoverability of the problem.

**Comment by bogdan-sava** [comment]
delayed by deactivateTemporary issue #1587

**Comment by bogdan-sava** [comment]
recheck

**Comment by bogdan-sava** [comment]
recheck

**Pull request merged**
